begin;
set local role postgres;
create extension if not exists pgtap with schema extensions;
set local search_path=pgtap,extensions,public;
select plan(48);

select has_table('public','accounting_settings','accounting settings exist');
select has_table('public','gl_accounts','chart of accounts exists');
select has_table('public','accounting_periods','periods exist');
select has_table('public','account_mappings','mappings exist');
select has_table('public','accounting_events','outbox exists');
select has_table('public','journal_entries','journals exist');
select has_table('public','journal_lines','journal lines exist');
select has_table('public','expenses','expenses exist');
select has_table('public','expense_documents','expense documents exist');
select has_table('public','bank_transfers','bank transfers exist');
select has_table('public','bank_statement_imports','bank imports exist');
select has_table('public','bank_statement_lines','bank lines exist');
select has_view('public','general_ledger','general ledger view exists');
select has_view('public','trial_balance','trial balance exists');
select has_view('public','financial_statement_balances','statement balances exist');
select has_view('public','finance_reconciliation','control reconciliation exists');
select has_view('public','bank_match_suggestions','bank suggestions exist');
select has_function('public','create_manual_journal',array['uuid','date','text','jsonb'],'manual journal API exists');
select has_function('public','reverse_journal',array['uuid','uuid','date','text'],'reversal API exists');
select has_function('public','post_expense',array['uuid','uuid'],'expense posting API exists');
select has_function('public','post_bank_transfer',array['uuid','uuid','date','uuid','uuid','numeric','text','numeric','text'],'transfer API exists');
select is((select count(*)::integer from public.permissions where code like 'finance.%'),18,'all finance capabilities exist');
select is((select relrowsecurity from pg_class where oid='public.journal_entries'::regclass),true,'journal RLS enabled');
select is((select relforcerowsecurity from pg_class where oid='public.journal_entries'::regclass),true,'journal RLS forced');
select is((select relrowsecurity from pg_class where oid='public.expenses'::regclass),true,'expense RLS enabled');
select is((select relforcerowsecurity from pg_class where oid='public.bank_statement_lines'::regclass),true,'bank RLS forced');

insert into auth.users(id,instance_id,aud,role,email,encrypted_password,email_confirmed_at,created_at,updated_at) values
('00000000-0000-4000-8000-00000000900a','00000000-0000-0000-0000-000000000000','authenticated','authenticated','finance-owner@example.test','',now(),now(),now()),
('00000000-0000-4000-8000-00000000900b','00000000-0000-0000-0000-000000000000','authenticated','authenticated','finance-outsider@example.test','',now(),now(),now());
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"00000000-0000-4000-8000-00000000900a","role":"authenticated"}',true);
select lives_ok($$select public.create_organization('Finance Test','finance-test','GB','GBP','Europe/London')$$,'finance tenant bootstraps');
set local role postgres;
select set_config('x.org',(select id::text from public.organizations where slug='finance-test'),true);
select set_config('x.business',(select id::text from public.businesses where organization_id=current_setting('x.org')::uuid limit 1),true);
insert into public.branches(id,organization_id,business_id,name,code,status,timezone,created_by) values('00000000-0000-4000-8000-000000009101',current_setting('x.org')::uuid,current_setting('x.business')::uuid,'Finance Branch','FIN','active','Europe/London','00000000-0000-4000-8000-00000000900a');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"00000000-0000-4000-8000-00000000900a","role":"authenticated"}',true);
select lives_ok(format($q$select public.initialize_accounting('%s','GBP',1,current_date)$q$,current_setting('x.org')),'accounting template initializes');
select is((select count(*)::integer from public.gl_accounts where organization_id=current_setting('x.org')::uuid),12,'generic chart has twelve starter accounts');
select is((select count(*)::integer from public.gl_accounts where organization_id=current_setting('x.org')::uuid and control_type is not null),6,'six protected control accounts exist');
select is((select count(*)::integer from public.accounting_periods where organization_id=current_setting('x.org')::uuid),24,'twenty-four periods generated');
select set_config('x.cash',(select public.create_gl_account(current_setting('x.org')::uuid,'1110','Main Bank','ASSET',null,'GBP','Bank')::text),true);
select set_config('x.expense',(select id::text from public.gl_accounts where organization_id=current_setting('x.org')::uuid and account_code='6100'),true);
select set_config('x.revenue',(select id::text from public.gl_accounts where organization_id=current_setting('x.org')::uuid and account_code='4100'),true);
select set_config('x.ar',(select id::text from public.gl_accounts where organization_id=current_setting('x.org')::uuid and account_code='1200'),true);
select set_config('x.payaccount',(select public.create_payment_account(current_setting('x.org')::uuid,'00000000-0000-4000-8000-000000009101','FIN-BANK','Finance Bank','BANK','GBP','Finance')::text),true);
select lives_ok(format($q$select public.map_payment_account('%s','%s','%s')$q$,current_setting('x.org'),current_setting('x.payaccount'),current_setting('x.cash')),'settlement account maps to GL');
select lives_ok(format($q$select public.activate_accounting('%s')$q$,current_setting('x.org')),'complete setup activates');
select is((select status from public.accounting_settings where organization_id=current_setting('x.org')::uuid),'ACTIVE','activation persists');
select set_config('x.journal',(select public.create_manual_journal(current_setting('x.org')::uuid,current_date,'Test balanced entry',jsonb_build_array(jsonb_build_object('account_id',current_setting('x.expense'),'debit',25),jsonb_build_object('account_id',current_setting('x.revenue'),'credit',25)))::text),true);
select is((select status from public.journal_entries where id=current_setting('x.journal')::uuid),'POSTED','manual journal posts');
select is((select sum(base_debit) from public.journal_lines where journal_id=current_setting('x.journal')::uuid),(select sum(base_credit) from public.journal_lines where journal_id=current_setting('x.journal')::uuid),'posted journal balances');
select throws_ok(format($q$select public.create_manual_journal('%s',current_date,'Bad',jsonb_build_array(jsonb_build_object('account_id','%s','debit',10),jsonb_build_object('account_id','%s','credit',9)))$q$,current_setting('x.org'),current_setting('x.expense'),current_setting('x.revenue')),'P0001','JOURNAL_UNBALANCED','unbalanced journal rejected');
select throws_ok(format($q$select public.create_manual_journal('%s',current_date,'Control',jsonb_build_array(jsonb_build_object('account_id','%s','debit',10),jsonb_build_object('account_id','%s','credit',10)))$q$,current_setting('x.org'),current_setting('x.ar'),current_setting('x.revenue')),'P0001','CONTROL_ACCOUNT_MANUAL_POST_BLOCKED','manual control posting blocked');
set local role postgres;
select throws_ok(format($q$update public.journal_lines set base_debit=30 where journal_id='%s'$q$,current_setting('x.journal')),'P0001','POSTED_JOURNAL_IMMUTABLE','journal line mutation blocked');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"00000000-0000-4000-8000-00000000900a","role":"authenticated"}',true);
select set_config('x.reversal',(select public.reverse_journal(current_setting('x.org')::uuid,current_setting('x.journal')::uuid,current_date,'Correct test')::text),true);
select is((select status from public.journal_entries where id=current_setting('x.journal')::uuid),'REVERSED','original marked reversed');
select is((select reversal_of_id from public.journal_entries where id=current_setting('x.reversal')::uuid),current_setting('x.journal')::uuid,'reversal links original');
select is((select coalesce(sum(debit_balance),0) from public.trial_balance where organization_id=current_setting('x.org')::uuid),(select coalesce(sum(credit_balance),0) from public.trial_balance where organization_id=current_setting('x.org')::uuid),'trial balance totals agree');
select set_config('x.period',(select id::text from public.accounting_periods where organization_id=current_setting('x.org')::uuid and current_date between start_date and end_date),true);
select lives_ok(format($q$select public.set_accounting_period_status('%s','%s','CLOSED')$q$,current_setting('x.org'),current_setting('x.period')),'period closes');
select throws_ok(format($q$select public.create_manual_journal('%s',current_date,'Closed entry',jsonb_build_array(jsonb_build_object('account_id','%s','debit',1),jsonb_build_object('account_id','%s','credit',1)))$q$,current_setting('x.org'),current_setting('x.expense'),current_setting('x.revenue')),'P0001','PERIOD_CLOSED','closed period rejects posting');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"00000000-0000-4000-8000-00000000900b","role":"authenticated"}',true);
select is((select count(*)::integer from public.gl_accounts where organization_id=current_setting('x.org')::uuid),0,'outsider cannot read chart');
select throws_ok(format($q$select public.create_gl_account('%s','9999','Intruder','EXPENSE',null,'','No')$q$,current_setting('x.org')),'42501','PERMISSION_DENIED','outsider cannot create account');
set local role anon;
select set_config('request.jwt.claims','{"role":"anon"}',true);
select throws_ok(format($q$select public.activate_accounting('%s')$q$,current_setting('x.org')),'42501','permission denied for function activate_accounting','anonymous cannot activate accounting');
set local role postgres;
select is((select count(*)::integer from public.audit_events where organization_id=current_setting('x.org')::uuid and action='finance.journal.posted'),2,'posting and reversal audited');
select * from finish();
rollback;
