begin;
set local role postgres;
create extension if not exists pgtap with schema extensions;
set local search_path=pgtap,extensions,public;
select plan(41);

select has_table('public','platform_admins','platform identities exist');
select has_table('public','platform_settings','platform settings exist');
select has_table('public','platform_features','feature registry exists');
select has_table('public','saas_plans','plans exist');
select has_table('public','plan_entitlements','plan entitlements exist');
select has_table('public','organization_subscriptions','subscriptions exist');
select has_table('public','organization_entitlement_overrides','overrides exist');
select has_table('public','platform_feature_flags','feature flags exist');
select has_table('public','platform_billing_transactions','billing history is separate');
select has_table('public','platform_webhook_events','webhook idempotency exists');
select has_table('public','platform_audit_events','platform audit exists');
select has_table('public','offline_entitlement_leases','offline leases exist');
select has_function('public','organization_access_mode',array['uuid'],'central access mode exists');
select has_function('public','organization_has_feature',array['uuid','text'],'feature check exists');
select has_function('public','assert_organization_feature',array['uuid','text','boolean'],'feature assertion exists');
select has_function('public','organization_usage',array['uuid'],'authoritative usage exists');
select has_function('public','assert_organization_limit',array['uuid','text','bigint'],'limit assertion exists');
select has_function('public','issue_offline_entitlement_lease',array['uuid','uuid'],'lease issue exists');
select has_function('public','offline_lease_allows_sale',array['uuid','uuid','timestamp with time zone'],'lease validation exists');
select has_function('public','platform_set_tenant_suspension',array['uuid','boolean','text'],'suspension API exists');
select is((select count(*)::integer from public.saas_plans where code in ('STARTER','GROWTH','BUSINESS')),3,'default plans are data');
select is((select count(*)::integer from public.platform_features where status='ACTIVE'),16,'canonical feature registry seeded');
select is((select relrowsecurity from pg_class where oid='public.platform_admins'::regclass),true,'admin RLS enabled');
select is((select relforcerowsecurity from pg_class where oid='public.platform_admins'::regclass),true,'admin RLS forced');
select is((select relforcerowsecurity from pg_class where oid='public.organization_subscriptions'::regclass),true,'subscription RLS forced');
select is((select relforcerowsecurity from pg_class where oid='public.platform_billing_transactions'::regclass),true,'billing RLS forced');
select is((select relforcerowsecurity from pg_class where oid='public.platform_audit_events'::regclass),true,'platform audit RLS forced');
select is((select count(*)::integer from pg_indexes where indexname='organization_one_live_subscription'),1,'one live subscription index exists');
select is((select count(*)::integer from pg_indexes where indexname='platform_billing_provider_reference_unique'),1,'provider reference unique');
select is((select count(*)::integer from pg_indexes where indexname='platform_feature_flags_org_unique'),1,'organization flag targeting unique');

insert into auth.users(id,instance_id,aud,role,email,encrypted_password,email_confirmed_at,created_at,updated_at) values
('00000000-0000-4000-8000-00000001000a','00000000-0000-0000-0000-000000000000','authenticated','authenticated','saas-owner@example.test','',now(),now(),now()),
('00000000-0000-4000-8000-00000001000b','00000000-0000-0000-0000-000000000000','authenticated','authenticated','saas-outsider@example.test','',now(),now(),now());
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"00000000-0000-4000-8000-00000001000a","role":"authenticated"}',true);
select lives_ok($$select public.create_organization('SaaS Test','saas-test','GB','GBP','Europe/London')$$,'organization and trial bootstrap atomically');
select set_config('x.org',(select id::text from public.organizations where slug='saas-test'),true);
select is((select status from public.organization_subscriptions where organization_id=current_setting('x.org')::uuid),'TRIALING','new organization starts trial');
select is(public.organization_access_mode(current_setting('x.org')::uuid),'FULL_ACCESS','valid trial has full access');
select ok(public.organization_has_feature(current_setting('x.org')::uuid,'finance'),'trial plan grants entitled feature');
select is((public.organization_usage(current_setting('x.org')::uuid)->>'branches')::integer,0,'usage derives live branches');
select set_config('request.jwt.claims','{"sub":"00000000-0000-4000-8000-00000001000b","role":"authenticated"}',true);
select is(public.organization_has_feature(current_setting('x.org')::uuid,'finance'),false,'cross-tenant entitlement denied');
select throws_ok(format($q$select public.platform_set_tenant_suspension('%s',true,'intrusion')$q$,current_setting('x.org')),'42501','PLATFORM_ADMIN_REQUIRED','tenant cannot call platform administration');
set local role postgres;
update public.organization_subscriptions set trial_ends_at=now()-interval '1 second' where organization_id=current_setting('x.org')::uuid;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"00000000-0000-4000-8000-00000001000a","role":"authenticated"}',true);
select is(public.organization_access_mode(current_setting('x.org')::uuid),'READ_ONLY','expired trial becomes read only');
select throws_ok(format($q$select public.assert_organization_feature('%s','sales',true)$q$,current_setting('x.org')),'42501','SUBSCRIPTION_EXPIRED','expired subscription blocks writes');
set local role postgres;
select lives_ok($$select public.record_platform_webhook_event('PAYSTACK','event-1','charge.success','abc')$$,'first webhook accepted');
select is(public.record_platform_webhook_event('PAYSTACK','event-1','charge.success','abc'),false,'duplicate webhook is idempotent');
select * from finish();
rollback;
