begin;
set local role postgres;
create extension if not exists pgtap with schema extensions;
set local search_path=pgtap,extensions,public;
select plan(42);

select has_table('public','pos_settings','POS settings table exists');
select has_table('public','pos_terminals','POS terminals table exists');
select has_table('public','pos_sessions','POS sessions table exists');
select has_table('public','pos_held_carts','held carts table exists');
select has_table('public','pos_sales','POS sales table exists');
select has_table('public','pos_sale_settlements','split settlements table exists');
select has_table('public','pos_cash_events','till event ledger exists');
select has_table('public','pos_receipt_reprints','receipt reprint audit exists');
select has_function('public','create_pos_terminal',array['uuid','uuid','text','text','uuid','uuid','uuid','uuid','text','text'],'terminal RPC exists');
select has_function('public','update_pos_terminal',array['uuid','uuid','text','text','uuid','uuid','text','text'],'terminal update RPC exists');
select has_function('public','open_pos_session',array['uuid','uuid','numeric','text'],'open session RPC exists');
select has_function('public','record_pos_cash_event',array['uuid','uuid','text','numeric','text'],'cash event RPC exists');
select has_function('public','close_pos_session',array['uuid','uuid','numeric','text','text'],'close session RPC exists');
select has_function('public','review_pos_session',array['uuid','uuid','boolean','text'],'session review RPC exists');
select has_function('public','hold_pos_cart',array['uuid','uuid','uuid','jsonb','text','uuid'],'hold cart RPC exists');
select has_function('public','abandon_pos_cart',array['uuid','uuid'],'abandon cart RPC exists');
select has_function('public','post_pos_sale',array['uuid','uuid','uuid','jsonb','jsonb','numeric','numeric','text','uuid','uuid'],'atomic checkout RPC exists');
select has_function('public','record_pos_receipt_reprint',array['uuid','uuid','text'],'receipt reprint RPC exists');
select has_function('public','record_pos_cash_refund',array['uuid','uuid','uuid'],'cash refund RPC exists');
select has_function('public','update_pos_settings',array['uuid','boolean','boolean','boolean','numeric','numeric','integer','text'],'POS settings RPC exists');
select has_view('public','pos_session_summaries','session summary view exists');
select has_view('public','pos_receipts','receipt view exists');
select has_view('public','pos_daily_summary','daily POS report exists');

insert into auth.users(id,instance_id,aud,role,email,encrypted_password,email_confirmed_at,created_at,updated_at) values
('00000000-0000-4000-8000-00000000700a','00000000-0000-0000-0000-000000000000','authenticated','authenticated','pos-owner@example.test','',now(),now(),now()),
('00000000-0000-4000-8000-00000000700b','00000000-0000-0000-0000-000000000000','authenticated','authenticated','pos-outsider@example.test','',now(),now(),now());
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"00000000-0000-4000-8000-00000000700a","role":"authenticated"}',true);
select lives_ok($$select public.create_organization('POS Test','pos-test','GB','GBP','Europe/London')$$,'POS tenant bootstraps');
set local role postgres;
select set_config('x.org',(select id::text from public.organizations where slug='pos-test'),true);
select set_config('x.business',(select id::text from public.businesses where organization_id=current_setting('x.org')::uuid limit 1),true);
insert into public.branches(id,organization_id,business_id,name,code,status,timezone,created_by) values('00000000-0000-4000-8000-000000007101',current_setting('x.org')::uuid,current_setting('x.business')::uuid,'POS Branch','POS1','active','Europe/London','00000000-0000-4000-8000-00000000700a');
insert into public.warehouses(id,organization_id,branch_id,business_id,name,code,warehouse_type,status,is_default,created_by) values('00000000-0000-4000-8000-000000007102',current_setting('x.org')::uuid,'00000000-0000-4000-8000-000000007101',current_setting('x.business')::uuid,'Shop Floor','SHOP','SHOP_FLOOR','active',true,'00000000-0000-4000-8000-00000000700a');
select set_config('x.location',(select id::text from public.storage_locations where warehouse_id='00000000-0000-4000-8000-000000007102' and location_type='ROOT'),true);
insert into public.customers(id,organization_id,customer_code,customer_type,display_name,default_currency,created_by) values('00000000-0000-4000-8000-000000007104',current_setting('x.org')::uuid,'WALK-IN','INDIVIDUAL','Walk-in Customer','GBP','00000000-0000-4000-8000-00000000700a');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"00000000-0000-4000-8000-00000000700a","role":"authenticated"}',true);
select set_config('x.account',(select public.create_payment_account(current_setting('x.org')::uuid,'00000000-0000-4000-8000-000000007101','TILL','Main Till','CASH','GBP','POS till')::text),true);
select lives_ok(format($q$select public.create_pos_terminal('%s','00000000-0000-4000-8000-000000007101','T1','Front Till','00000000-0000-4000-8000-000000007102','%s','00000000-0000-4000-8000-000000007104','%s','80MM','Thank you')$q$,current_setting('x.org'),current_setting('x.location'),current_setting('x.account')),'authorized owner creates terminal');
select set_config('x.terminal',(select id::text from public.pos_terminals where organization_id=current_setting('x.org')::uuid and terminal_code='T1'),true);
select is((select status from public.pos_terminals where id=current_setting('x.terminal')::uuid),'ACTIVE','terminal is active');
select lives_ok(format($q$select public.open_pos_session('%s','%s',100,'Opening')$q$,current_setting('x.org'),current_setting('x.terminal')),'cashier opens till session');
select set_config('x.session',(select id::text from public.pos_sessions where terminal_id=current_setting('x.terminal')::uuid and status='OPEN'),true);
select is((select status from public.pos_sessions where id=current_setting('x.session')::uuid),'OPEN','session state is open');
select throws_ok(format($q$select public.open_pos_session('%s','%s',0,'Duplicate')$q$,current_setting('x.org'),current_setting('x.terminal')),'P0001','POS_SESSION_ALREADY_OPEN','terminal cannot have two open sessions');
select lives_ok(format($q$select public.record_pos_cash_event('%s','%s','CASH_IN',50,'Extra float')$q$,current_setting('x.org'),current_setting('x.session')),'cash in is recorded');
select is(public.pos_expected_cash(current_setting('x.session')::uuid),150::numeric,'expected cash derives from immutable till events');
select lives_ok(format($q$select public.hold_pos_cart('%s','%s','00000000-0000-4000-8000-000000007104','[{"product":"fixture","quantity":1}]','Customer paused',null)$q$,current_setting('x.org'),current_setting('x.session')),'cart can be held');
select is((select status from public.pos_held_carts where session_id=current_setting('x.session')::uuid),'HELD','held cart state is explicit');
select throws_ok(format($q$select public.close_pos_session('%s','%s',100,'Close','')$q$,current_setting('x.org'),current_setting('x.session')),'P0001','CASH_VARIANCE_REASON_REQUIRED','variance requires a reason');
select lives_ok(format($q$select public.close_pos_session('%s','%s',100,'Close','Count was short')$q$,current_setting('x.org'),current_setting('x.session')),'session closes into review when variance exceeds tolerance');
select is((select status from public.pos_sessions where id=current_setting('x.session')::uuid),'REVIEW_REQUIRED','variance produces review state');
select lives_ok(format($q$select public.review_pos_session('%s','%s',true,'Approved after recount')$q$,current_setting('x.org'),current_setting('x.session')),'authorized reviewer approves variance');
select is((select status from public.pos_sessions where id=current_setting('x.session')::uuid),'CLOSED','reviewed session becomes closed');
select throws_ok(format($q$insert into public.pos_sessions(organization_id,branch_id,terminal_id,cashier_user_id,session_number,opening_float) values('%s','00000000-0000-4000-8000-000000007101','%s','00000000-0000-4000-8000-00000000700a','DIRECT',0)$q$,current_setting('x.org'),current_setting('x.terminal')),'42501',null,'direct session insertion is blocked');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"00000000-0000-4000-8000-00000000700b","role":"authenticated"}',true);
select throws_ok(format($q$select public.open_pos_session('%s','%s',0,'Outsider')$q$,current_setting('x.org'),current_setting('x.terminal')),'42501','UNAUTHORIZED_TERMINAL','cross-tenant outsider cannot open terminal');
set local role anon;
select set_config('request.jwt.claims','{"role":"anon"}',true);
select throws_ok(format($q$select public.record_pos_receipt_reprint('%s',gen_random_uuid(),'Anon')$q$,current_setting('x.org')),'42501',null,'anonymous caller cannot invoke receipt RPC');
set local role postgres;
select is((select count(*) from public.audit_events where organization_id=current_setting('x.org')::uuid and action like 'pos.%')>=5,true,'POS administration and till lifecycle are audited');
select * from finish();
rollback;
