import Link from "next/link";
import { PageHeader } from "@/components/ui/page-header";
import { StatusBadge } from "@/components/ui/status-badge";
import { cancelAtPeriodEnd, requestPlanChange } from "@/features/subscriptions/actions";
import { formatBillingInterval, remainingDays, usageState } from "@/features/subscriptions/domain";
import { subscriptionErrorMessage } from "@/features/subscriptions/errors";
import { getTenantBilling } from "@/features/subscriptions/queries";

const usageKeys = [["branches", "multi_branch", "Branches"], ["staff", "staff", "Team members"], ["warehouses", "warehouses", "Warehouses"], ["pos_terminals", "pos_terminals", "POS terminals"], ["offline_devices", "offline_devices", "Offline devices"]] as const;
export default async function BillingPage({ searchParams }: { searchParams: Promise<{ error?: string; cancelled?: string; checkout?: string }> }) {
  const [data, query] = await Promise.all([getTenantBilling(), searchParams]); const subscription = data.subscription; const currentPlan = subscription?.saas_plans;
  const currentEntitlements = data.plans.find((plan) => plan.id === subscription?.plan_id)?.plan_entitlements ?? [];
  return <><PageHeader eyebrow="Settings · Billing & Plan" title="Billing and subscription" description="Manage the commercial plan for your organization. Subscription billing remains separate from customer and supplier payments." />
    {query.error && <p className="mt-5 rounded-xl bg-warning-soft p-4 text-warning">{subscriptionErrorMessage(query.error)}</p>}
    {query.checkout && <p className="mt-5 rounded-xl bg-muted p-4">Provider checkout is not configured. No subscription change or charge was made.</p>}
    <section className="mt-6 grid gap-4 lg:grid-cols-[1.3fr_1fr]">
      <article className="rounded-2xl border bg-surface p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-subtle">Current plan</p><h2 className="mt-1 text-2xl font-semibold">{currentPlan?.name ?? "No plan"}</h2></div><StatusBadge tone={subscription?.access_mode === "FULL_ACCESS" ? "positive" : "warning"}>{subscription?.status ?? "SUBSCRIPTION REQUIRED"}</StatusBadge></div>
        {subscription && <dl className="mt-6 grid gap-4 sm:grid-cols-2"><Item label="Access mode" value={subscription.access_mode}/><Item label="Billing" value={formatBillingInterval(subscription.billing_interval)}/><Item label="Renewal / end" value={subscription.current_period_end ? new Date(subscription.current_period_end).toLocaleDateString() : "—"}/><Item label="Trial remaining" value={`${remainingDays(subscription.trial_ends_at ? new Date(subscription.trial_ends_at) : null)} days`}/></dl>}
        {subscription && !subscription.cancel_at_period_end && <form action={cancelAtPeriodEnd} className="mt-6"><button className="rounded-xl border px-4 py-2 text-sm font-semibold">Cancel at period end</button></form>}{subscription?.cancel_at_period_end && <p className="mt-6 text-sm text-warning">Cancellation is scheduled for the end of the current period. Your data will be retained.</p>}
      </article>
      <article className="rounded-2xl border bg-surface p-6"><h2 className="font-semibold">Current usage</h2><div className="mt-4 space-y-4">{usageKeys.map(([usageKey, featureCode, label]) => { const value = Number((data.usage as Record<string, number>)[usageKey] ?? 0); const entitlement = currentEntitlements.find((item) => item.feature_code === featureCode); const state = usageState(value, entitlement?.numeric_value == null ? null : Number(entitlement.numeric_value)); return <div key={usageKey}><div className="flex justify-between text-sm"><span>{label}</span><strong className={state.overLimit ? "text-warning" : ""}>{state.label}</strong></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-muted"><div className={`h-full ${state.nearLimit ? "bg-warning" : "bg-accent"}`} style={{ width: `${Math.min(100, state.ratio * 100)}%` }}/></div></div>})}</div></article>
    </section>
    <section className="mt-8"><h2 className="text-xl font-semibold">Compare plans</h2><div className="mt-4 grid gap-4 lg:grid-cols-3">{data.plans.map((plan) => <article key={plan.id} className={`rounded-2xl border bg-surface p-5 ${plan.id === subscription?.plan_id ? "border-accent" : ""}`}><div className="flex justify-between"><h3 className="text-lg font-semibold">{plan.name}</h3>{plan.id === subscription?.plan_id && <StatusBadge tone="positive">Current</StatusBadge>}</div><p className="mt-2 min-h-10 text-sm text-subtle">{plan.description}</p><p className="mt-5 text-2xl font-semibold">{plan.currency} {Number(plan.monthly_price).toFixed(2)}<span className="text-sm font-normal text-subtle"> / month</span></p><p className="mt-1 text-sm text-subtle">{plan.currency} {Number(plan.annual_price).toFixed(2)} annually</p><ul className="mt-5 space-y-2 text-sm">{plan.plan_entitlements.filter((e) => e.enabled || Number(e.numeric_value) > 0).slice(0, 8).map((e) => <li key={e.feature_code}>✓ {e.feature_code.replaceAll("_", " ")}{e.numeric_value != null ? ` · ${Number(e.numeric_value)}` : ""}</li>)}</ul>{plan.id !== subscription?.plan_id && <form action={requestPlanChange} className="mt-6"><input type="hidden" name="planId" value={plan.id}/><select name="interval" className="w-full rounded-xl border bg-surface px-3 py-2"><option value="MONTHLY">Monthly</option><option value="ANNUAL">Annual</option></select><button className="mt-3 w-full rounded-xl bg-accent px-4 py-2 font-semibold text-white">Choose {plan.name}</button></form>}</article>)}</div></section>
    <section className="mt-8 rounded-2xl border bg-surface p-6"><div className="flex justify-between"><h2 className="font-semibold">Billing history</h2><Link href="/dashboard/finance/export?type=ledger" className="text-sm text-accent">Export tenant data</Link></div><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="py-3">Date</th><th>Plan</th><th>Amount</th><th>Status</th><th>Reference</th></tr></thead><tbody>{data.billing.map((row) => <tr className="border-b" key={row.id}><td className="py-3">{new Date(row.created_at).toLocaleDateString()}</td><td>{row.saas_plans?.name}</td><td>{row.currency} {Number(row.amount).toFixed(2)}</td><td>{row.status}</td><td>{row.provider_reference ?? "—"}</td></tr>)}</tbody></table>{!data.billing.length && <p className="py-6 text-sm text-subtle">No platform billing transactions yet.</p>}</div></section></>;
}
function Item({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs uppercase tracking-wide text-subtle">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>; }
