import Link from "next/link";
import { PrintButton } from "@/components/ui/print-button";
import { PageHeader } from "@/components/ui/page-header";
import { balanceSheet, formatMoney, profitAndLoss, trialBalanceTotals } from "@/features/finance/calculations";
import { financeData } from "@/features/finance/queries";

export default async function ReportsPage() {
  const data = await financeData();
  const totals = trialBalanceTotals(data.trial);
  const pnl = profitAndLoss(data.balances);
  const sheet = balanceSheet(data.balances);
  const currency = data.organization.currency_code;
  const cashMovement = data.balances.filter((row) => row.account_type === "ASSET" && /cash|bank/i.test(row.name ?? "")).reduce((total, row) => total + Number(row.balance), 0);
  return <><PageHeader eyebrow="Finance" title="Financial reports" description="Management reports derived from posted General Ledger lines, never direct sales totals." actions={<PrintButton />} /><section className="app-surface overflow-hidden"><ReportHeader title="Trial balance" description="Debit and credit balances by account." exportName="trial-balance" /><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th>Account</th><th className="text-right">Debit</th><th className="text-right">Credit</th></tr></thead><tbody>{data.trial.map((row) => <tr key={`${row.account_code}-${row.name}`}><td><span className="font-mono text-xs text-subtle">{row.account_code}</span> <strong>{row.name}</strong></td><td className="text-right font-mono">{formatMoney(Number(row.debit_balance), currency)}</td><td className="text-right font-mono">{formatMoney(Number(row.credit_balance), currency)}</td></tr>)}</tbody><tfoot><tr className="bg-muted font-semibold"><th>Totals</th><td className="p-4 text-right font-mono">{formatMoney(totals.debit, currency)}</td><td className="p-4 text-right font-mono">{formatMoney(totals.credit, currency)}</td></tr></tfoot></table></div></section><div className="grid gap-6 xl:grid-cols-2"><Statement title="Profit & loss" description="Operating performance from posted income and expense accounts." exportName="profit-loss" rows={[["Revenue", pnl.revenue], ["Operating expenses and cost of goods", pnl.expenses], ["Net result", pnl.netProfit]]} currency={currency} emphasize="Net result" /><Statement title="Balance sheet" description="Assets, liabilities and equity at the reporting point." exportName="balance-sheet" rows={[["Assets", sheet.assets], ["Liabilities", sheet.liabilities], ["Equity", sheet.equity], ["Current earnings", sheet.currentEarnings], ["Equation difference", sheet.difference]]} currency={currency} emphasize="Equation difference" /><Statement title="Cash flow" description="Initial non-statutory categorized cash movement. Advanced indirect adjustments remain outside the current boundary." exportName="cash-flow" rows={[["Net cash movement", cashMovement]]} currency={currency} emphasize="Net cash movement" /></div></>;
}

function ReportHeader({ title, description, exportName }: { title: string; description: string; exportName: string }) { return <header className="flex flex-wrap items-start justify-between gap-4 border-b p-5"><div><h2 className="font-semibold">{title}</h2><p className="mt-1 text-sm text-subtle">{description}</p></div><Link className="rounded-lg border px-3 py-2 text-xs font-semibold" href={`/dashboard/finance/export?report=${exportName}`}>Export CSV</Link></header>; }
function Statement({ title, description, exportName, rows, currency, emphasize }: { title: string; description: string; exportName: string; rows: Array<[string, number]>; currency: string; emphasize: string }) { return <section className="app-surface overflow-hidden"><ReportHeader title={title} description={description} exportName={exportName} /><dl>{rows.map(([label, value]) => <div key={label} className={`flex items-center justify-between gap-5 border-t px-5 py-4 first:border-0 ${label === emphasize ? "bg-muted" : ""}`}><dt className={label === emphasize ? "font-semibold" : "text-subtle"}>{label}</dt><dd className="font-mono font-semibold">{formatMoney(value, currency)}</dd></div>)}</dl></section>; }
