import Link from "next/link";
import { DocumentBrand } from "@/components/brand/inventman-logo";
import { Button } from "@/components/ui/button";
import { PrintButton } from "@/features/sales/components/print-button";
import { allocatePayment, postRefund, reversePayment } from "../actions";

type Detail = NonNullable<Awaited<ReturnType<typeof import("../queries").paymentDetail>>["payment"]>;

export function PaymentDetail({ payment, kind, openInvoices, accounts, methods }: { payment: Detail; kind: "CUSTOMER" | "SUPPLIER"; openInvoices: Array<{ id: string; invoice_number: string; outstanding_base: number }>; accounts: Array<{ id: string; name: string }>; methods: Array<{ id: string; name: string }> }) {
  const allocated = payment.payment_allocations.filter((x) => !x.is_reversal).reduce((sum, x) => sum + Number(x.allocated_amount), 0);
  const unallocated = Math.max(0, Number(payment.amount) - allocated);
  const base = kind === "CUSTOMER" ? "/dashboard/sales/payments" : "/dashboard/procurement/payments";
  const party = kind === "CUSTOMER" ? payment.customers?.display_name : payment.suppliers?.legal_name;
  return <div className="space-y-7 print:p-0">
    <DocumentBrand />
    <div className="flex flex-wrap justify-between gap-4"><div><p className="text-sm font-semibold text-accent">{kind === "CUSTOMER" ? "Customer receipt" : "Supplier payment voucher"}</p><h1 className="mt-2 text-3xl font-semibold">{payment.payment_number}</h1><p className="mt-2 text-subtle">{party} · {payment.branches?.name}</p></div><div className="print:hidden"><PrintButton label={kind === "CUSTOMER" ? "Print receipt" : "Print voucher"} /></div></div>
    <section className="grid gap-4 rounded-2xl border bg-surface p-5 sm:grid-cols-2 lg:grid-cols-4">{[["Status", payment.status],["Amount", `${payment.currency} ${Number(payment.amount).toLocaleString()}`],["Allocated", `${payment.currency} ${allocated.toLocaleString()}`],["Unallocated", `${payment.currency} ${unallocated.toLocaleString()}`],["Method", payment.payment_methods?.name],["Account", payment.payment_accounts?.name],["Reference", payment.external_reference || "—"],["Date", payment.payment_date]].map(([label,value]) => <div key={label}><p className="text-xs uppercase text-subtle">{label}</p><p className="mt-1 font-semibold">{value}</p></div>)}</section>
    <section className="rounded-2xl border p-5"><h2 className="font-semibold">Allocations</h2><div className="mt-3 space-y-2">{payment.payment_allocations.filter((x) => !x.is_reversal).map((x) => <div key={x.id} className="flex justify-between rounded-lg bg-muted p-3 text-sm"><span>{x.customer_invoices?.invoice_number ?? x.supplier_invoices?.invoice_number}</span><strong>{payment.currency} {Number(x.allocated_amount).toLocaleString()}</strong></div>)}{!payment.payment_allocations.length && <p className="text-sm text-subtle">No allocations yet.</p>}</div></section>
    {unallocated > 0 && !["VOIDED","REFUNDED"].includes(payment.status) && <section className="grid gap-5 lg:grid-cols-2 print:hidden"><form action={allocatePayment.bind(null,kind,payment.id)} className="rounded-2xl border p-5"><h2 className="font-semibold">Allocate remaining payment</h2><div className="mt-3 space-y-2">{openInvoices.map((invoice) => <label key={invoice.id} className="flex justify-between gap-3 text-sm"><span>{invoice.invoice_number} · {invoice.outstanding_base}</span><input aria-label={`Allocate to ${invoice.invoice_number}`} name={`allocation:${invoice.id}`} type="number" min="0" max={Math.min(unallocated,Number(invoice.outstanding_base))} step="0.01" className="w-28 rounded border px-2" /></label>)}</div><Button className="mt-4">Allocate</Button></form>{kind === "CUSTOMER" && payment.customer_id && <form action={postRefund.bind(null,payment.id,payment.customer_id)} className="rounded-2xl border p-5"><h2 className="font-semibold">Refund unapplied credit</h2><input type="hidden" name="branchId" value={payment.branch_id}/><input type="hidden" name="currency" value={payment.currency}/><input type="hidden" name="exchangeRate" value={payment.exchange_rate_snapshot}/><div className="mt-3 grid gap-3 sm:grid-cols-2"><input aria-label="Refund date" name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)} required className="rounded border p-2"/><input aria-label="Refund amount" name="amount" type="number" max={unallocated} min="0.01" step="0.01" required className="rounded border p-2"/><select aria-label="Refund method" name="methodId" required className="rounded border p-2"><option value="">Method</option>{methods.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select aria-label="Refund account" name="accountId" required className="rounded border p-2"><option value="">Account</option>{accounts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input aria-label="Refund reference" name="reference" className="rounded border p-2"/><input aria-label="Refund reason" name="reason" required className="rounded border p-2"/></div><Button className="mt-4">Record refund</Button></form>}</section>}
    {!payment.is_reversal && payment.status !== "VOIDED" && <form action={reversePayment.bind(null,kind,payment.id)} className="flex flex-wrap gap-3 rounded-2xl border border-danger p-5 print:hidden"><input aria-label="Reversal reason" name="reason" required placeholder="Reason for reversal" className="min-h-10 flex-1 rounded-lg border px-3"/><Button type="submit" variant="secondary">Reverse payment</Button></form>}
    <Link href={base} className="inline-block text-sm font-semibold text-accent print:hidden">← Back to payments</Link>
  </div>;
}
