import Link from "next/link";
import { ArrowRight, BarChart3, Boxes, Building2, Check, Menu, Search, ShieldCheck, ShoppingCart, Wifi, X } from "lucide-react";
import type { ReactNode } from "react";
import { featurePages, industryPages } from "@/lib/marketing/content";
import { StructuredData } from "./structured-data";
import { PublicAnalytics } from "./public-analytics";

const links = [["Features", "/features"], ["Industries", "/industries"], ["Pricing", "/pricing"], ["Resources", "/resources"], ["Security", "/security"]] as const;
export function Brand() { return <Link className="brand" href="/" aria-label="Inventman home"><span aria-hidden="true">I</span>Inventman</Link>; }
export function PublicHeader() { return <header className="public-header-shell"><div className="public-header"><Brand /><nav aria-label="Primary navigation" className="desktop-public-nav">{links.map(([name, href]) => <Link key={href} href={href}>{name}</Link>)}</nav><div className="header-actions"><Link className="login-link" href="/login">Log in</Link><Link className="public-button public-button-sm" href="/signup">Start Free Trial</Link></div><details className="mobile-public-nav"><summary aria-label="Open navigation"><Menu className="menu-open" aria-hidden="true" /><X className="menu-close" aria-hidden="true" /></summary><nav aria-label="Mobile navigation">{links.map(([name, href]) => <Link key={href} href={href}>{name}</Link>)}<Link href="/login">Log in</Link><Link className="public-button" href="/signup">Start Free Trial</Link></nav></details></div></header>; }
export function PublicFooter() { return <footer className="public-footer-shell"><div className="public-footer"><div className="footer-brand"><Brand /><p>Business inventory, sales and profitability control from one connected platform.</p></div><div><strong>Product</strong><Link href="/features">Features</Link><Link href="/pricing">Pricing</Link><Link href="/security">Security</Link></div><div><strong>Solutions</strong>{industryPages.slice(0, 5).map((page) => <Link key={page.slug} href={`/industries/${page.slug}`}>{page.name}</Link>)}</div><div><strong>Resources</strong><Link href="/resources">Guides</Link><Link href="/support">Support</Link></div><div><strong>Company</strong><Link href="/about">About</Link><Link href="/contact">Contact</Link></div><div><strong>Legal</strong><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></div><p className="footer-note">© {new Date().getUTCFullYear()} Inventman. Production legal and contact information remains subject to owner approval.</p></div></footer>; }
export function PublicPage({ children, schema }: { children: ReactNode; schema?: Record<string, unknown> | Array<Record<string, unknown>> }) { return <><PublicAnalytics /><PublicHeader />{schema && <StructuredData data={schema} />}<main id="main-content">{children}</main><PublicFooter /></>; }
export function PageIntro({ eyebrow, title, body, actions }: { eyebrow: string; title: string; body: string; actions?: ReactNode }) { return <section className="page-intro"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{body}</p>{actions && <div className="hero-actions">{actions}</div>}</section>; }
export function PrimaryCta({ label = "Start Free Trial", href = "/signup" }: { label?: string; href?: string }) { return <Link className="public-button" href={href} data-analytics="PUBLIC_CTA">{label}<ArrowRight aria-hidden="true" className="size-4" /></Link>; }
export function TextCta({ label, href }: { label: string; href: string }) { return <Link className="text-link" href={href}>{label}<ArrowRight aria-hidden="true" className="size-4" /></Link>; }
export function FinalCta({ title = "Run your business with better visibility.", body = "Start a configured trial and build your workspace around the way your business actually runs." }: { title?: string; body?: string }) { return <section className="final-cta"><div><p className="eyebrow">Make the next decision with clarity</p><h2>{title}</h2><p>{body}</p></div><PrimaryCta /></section>; }
export function Breadcrumbs({ items }: { items: Array<{ name: string; href?: string }> }) { return <nav className="breadcrumbs" aria-label="Breadcrumb">{items.map((item, index) => <span key={item.name}>{index > 0 && <span aria-hidden="true">/</span>}{item.href ? <Link href={item.href}>{item.name}</Link> : <span aria-current="page">{item.name}</span>}</span>)}</nav>; }
export function Faq({ items }: { items: Array<{ question: string; answer: string }> }) { return <section className="section faq-section"><div className="section-heading"><p className="eyebrow">Questions, answered</p><h2>Practical answers before you start.</h2></div><div className="faq-list">{items.map((item) => <details key={item.question}><summary>{item.question}</summary><p>{item.answer}</p></details>)}</div></section>; }
export function CheckList({ items }: { items: readonly string[] }) { return <ul className="check-list">{items.map((item) => <li key={item}><Check aria-hidden="true" />{item}</li>)}</ul>; }
export const capabilityIcons = [Boxes, ShoppingCart, BarChart3, Building2, ShieldCheck];
export function RelatedFeatures({ slugs }: { slugs: string[] }) { const pages = featurePages.filter((page) => slugs.includes(page.slug)); return <section className="section related-section"><div className="section-heading"><p className="eyebrow">Connected capabilities</p><h2>Keep the workflow moving.</h2></div><div className="card-grid three">{pages.map((page) => <article className="link-card" key={page.slug}><h3>{page.name}</h3><p>{page.intro}</p><TextCta href={`/features/${page.slug}`} label={`Explore ${page.name.toLowerCase()}`} /></article>)}</div></section>; }

export function ProductFrame({ variant = "inventory", title = "Inventory overview" }: { variant?: "inventory" | "pos" | "finance" | "branches"; title?: string }) {
  const rows = variant === "finance" ? [["Revenue", "₦8,420,000"], ["Cost of sales", "₦5,180,000"], ["Operating expenses", "₦860,000"], ["Operating result", "₦2,380,000"]] : variant === "branches" ? [["Main Branch", "98.4% available"], ["Lekki Branch", "12 low-stock lines"], ["Ibadan Branch", "Reconciled"]] : [["Premium Rice 25kg", "184 available"], ["Fresh Milk 1L", "42 available"], ["Cooking Oil 5L", "Low stock"], ["Wireless Earbuds", "31 available"]];
  return <div className={`product-frame product-frame-${variant}`} aria-label={`${title} interface preview`}><div className="product-frame-bar"><span><i />Inventman</span><small>{title}</small><span className="frame-status"><Wifi aria-hidden="true" /> Connected</span></div>{variant === "pos" ? <div className="pos-frame"><div className="pos-products"><label><Search aria-hidden="true" />Search products or scan barcode</label>{[["Premium Rice 25kg", "₦38,500"], ["Fresh Milk 1L", "₦2,450"], ["Cooking Oil 5L", "₦14,800"]].map(([name, price]) => <div key={name}><span>{name}</span><strong>{price}</strong></div>)}</div><aside><p>Current sale</p><div><span>Premium Rice 25kg × 1</span><strong>₦38,500</strong></div><div><span>Fresh Milk 1L × 2</span><strong>₦4,900</strong></div><footer><span>Total</span><strong>₦43,400</strong><button type="button">Take payment</button></footer></aside></div> : <><div className="frame-metrics"><div><span>{variant === "finance" ? "Cash position" : variant === "branches" ? "Active branches" : "Stock on hand"}</span><strong>{variant === "finance" ? "₦4.82m" : variant === "branches" ? "3" : "12,480"}</strong><small>{variant === "finance" ? "Across controlled accounts" : variant === "branches" ? "6 warehouses connected" : "Across all warehouses"}</small></div><div><span>{variant === "finance" ? "Receivables" : variant === "branches" ? "Stock alerts" : "Low stock"}</span><strong>{variant === "finance" ? "₦1.24m" : variant === "branches" ? "18" : "18 lines"}</strong><small>Requires attention</small></div></div><div className="frame-table"><div className="frame-table-head"><span>{variant === "finance" ? "Management statement" : variant === "branches" ? "Branch performance" : "Product"}</span><span>{variant === "finance" ? "Current period" : "Status"}</span></div>{rows.map(([name, value], index) => <div key={name}><span><i>{String(index + 1).padStart(2, "0")}</i>{name}</span><strong className={value.includes("Low") ? "warning-text" : ""}>{value}</strong></div>)}</div></>}</div>;
}
