import { BarChart3, Boxes, Building2, CircleDollarSign, PackageCheck, ScanLine, ShieldCheck, ShoppingCart, Users } from "lucide-react";
import Link from "next/link";
import { CheckList, Faq, FinalCta, PrimaryCta, ProductFrame, PublicPage, TextCta } from "@/components/marketing/public-shell";
import { StructuredData } from "@/components/marketing/structured-data";
import { industryPages } from "@/lib/marketing/content";
import { absoluteUrl, faqSchema, productCategory, publicMetadata } from "@/lib/marketing/seo";

export const metadata = publicMetadata({ title: "Inventman — Inventory, Sales & Profitability Software", description: "Control stock, purchasing, sales, POS, cash, expenses, teams and profitability across your business with Inventman.", path: "/" });
const faqs = [
  { question: "What is Inventman?", answer: "Inventman is a business inventory, sales and profitability operating system. It connects stock, purchasing, sales, POS, payments, expenses, teams and financial reporting." },
  { question: "Who is Inventman for?", answer: "Inventman is designed for inventory-based small and growing businesses, including retailers, supermarkets, hospitality operators, pharmacies, electronics stores, wholesalers and multi-branch teams." },
  { question: "Does Inventman include POS?", answer: "Yes. Inventman includes controlled cashier sessions, product search, payments and receipts connected to stock movement." },
  { question: "Can Inventman work without internet?", answer: "Provisioned POS devices can continue supported offline cash sales during temporary connectivity loss and synchronize safely later. The wider workspace remains online-first." },
  { question: "Can I manage multiple branches?", answer: "Yes. Inventman supports branch-level warehouses, stock, users and operating records inside one organization." },
  { question: "Can Inventman track suppliers, receivables and payables?", answer: "Yes. Purchasing and supplier workflows connect to invoices, payments and payables, while customer sales connect to invoices, receipts and receivables." },
  { question: "Can Inventman track expenses and profitability?", answer: "Yes. Supported sales, inventory cost, payment and expense activity feeds management financial reporting. Inventman does not claim statutory filing or tax certification." },
  { question: "How does the free trial work?", answer: "Available trial length and plan limits come from Inventman’s current public plan configuration. Account creation does not take payment." },
];
const capabilities = [[Boxes,"Inventory","Balances, movements, counts, transfers and valuation."],[ShoppingCart,"Purchasing","Suppliers, approvals, orders, receiving and returns."],[PackageCheck,"Sales","Customers, orders, fulfilment, invoices and receivables."],[ScanLine,"POS","Cashier sessions, payments, receipts and supported offline sales."],[CircleDollarSign,"Payments & expenses","Collections, supplier payments, refunds and operating spend."],[BarChart3,"Finance","Journals, reconciliation and management financial reports."],[Users,"Teams","Roles, permissions, approvals and accountable activity."],[Building2,"Branches","Local stock and access with organization-wide visibility."]] as const;

export default function Home() {
  const base = absoluteUrl("/");
  return <PublicPage><StructuredData data={[{ "@context":"https://schema.org", "@type":"Organization", name:"Inventman", url:base },{ "@context":"https://schema.org", "@type":"WebSite", name:"Inventman", url:base, description:productCategory },{ "@context":"https://schema.org", "@type":"SoftwareApplication", name:"Inventman", applicationCategory:"BusinessApplication", operatingSystem:"Web", url:base, description:productCategory },faqSchema(faqs)]} />
    <section className="hero"><div className="hero-copy"><p className="eyebrow">Inventory · Sales · POS · Finance</p><h1>Control your stock, sales, cash and profitability from one business platform.</h1><p>Inventman connects inventory, purchasing, sales, POS, payments, expenses and financial reporting so growing businesses understand what they have, what they sell and what they earn.</p><div className="hero-actions"><PrimaryCta /><TextCta href="/features" label="Explore Inventman" /></div><div className="hero-proof"><ShieldCheck aria-hidden="true" /><span>Role-based access</span><span>Branch controls</span><span>Offline-supported POS</span></div></div><ProductFrame title="Operations overview" /></section>
    <section className="problem-band"><div><p className="eyebrow">Operational clarity</p><h2>Running a business should not mean guessing what is happening.</h2></div><div className="problem-list">{["Stock disappears without explanation","Sales happen but profit remains unclear","Purchases and suppliers become difficult to track","Branches operate without complete visibility","Cash moves without enough accountability"].map((problem,index)=><p key={problem}><span>0{index+1}</span>{problem}</p>)}</div></section>
    <section className="operating-cycle"><p className="eyebrow">One connected operating cycle</p><div>{["Purchase","Receive","Stock","Sell","Collect","Account","Report"].map((step,index)=><span key={step}>{step}{index<6&&<i aria-hidden="true">→</i>}</span>)}</div><p>Every handoff stays connected to the same operational record.</p></section>
    <section className="section"><div className="section-heading split"><div><p className="eyebrow">One operating picture</p><h2>Every core workflow stays connected.</h2></div><p>Keep the relationship between physical stock, commercial activity, cash and performance without turning the product into a wall of disconnected tools.</p></div><div className="platform-grid">{capabilities.map(([Icon,title,body])=><article key={title}><span><Icon aria-hidden="true" /></span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section className="section product-story"><div><p className="eyebrow">Inventory control</p><h2>Know exactly what you have—and where it is.</h2><p>See on-hand, reserved and available quantities across warehouses, then follow every count, transfer and adjustment through a clear movement history.</p><TextCta href="/features/inventory-management" label="Explore inventory control" /></div><ProductFrame variant="inventory" title="Inventory by warehouse" /></section>
    <section className="section product-story reverse"><ProductFrame variant="pos" title="Point of sale" /><div><p className="eyebrow">Fast, controlled checkout</p><h2>Sell quickly. Stay in control.</h2><p>Move from product search to payment and receipt while stock and cashier activity stay connected. Provisioned devices support bounded offline cash sales during connectivity loss.</p><TextCta href="/features/point-of-sale" label="Explore point of sale" /></div></section>
    <section className="finance-story"><div><p className="eyebrow">From operations to performance</p><h2>Understand what your business is actually earning.</h2><p>Supported stock, sales, payments and expenses feed controlled journals and management reporting, helping teams understand more than revenue alone.</p><TextCta href="/features/financial-reporting" label="Explore financial reporting" /></div><ProductFrame variant="finance" title="Profit and loss" /></section>
    <section className="section product-story"><div><p className="eyebrow">Multi-branch visibility</p><h2>See the whole operation while preserving local responsibility.</h2><p>Give each location the right operating context while leadership follows branches, warehouses, stock exceptions and performance from one organization.</p><TextCta href="/features/multi-branch-management" label="Explore branch control" /></div><ProductFrame variant="branches" title="Branch performance" /></section>
    <section className="section industry-section"><div className="section-heading split"><div><p className="eyebrow">Built around real operations</p><h2>Designed for businesses where stock has to move.</h2></div><TextCta href="/industries" label="View all industries" /></div><div className="industry-grid">{industryPages.map((page)=><Link key={page.slug} href={`/industries/${page.slug}`}><span>{page.name}</span><span aria-hidden="true">↗</span></Link>)}</div></section>
    <section className="security-callout section"><div><ShieldCheck aria-hidden="true" /><p className="eyebrow">Your business data should remain your business data</p><h2>Private records, role-aware access and traceable workflows.</h2></div><CheckList items={["Database-enforced tenant isolation","Secure authentication and controlled sessions","Role and branch-aware permissions","Auditable operational and financial activity"]} /><TextCta href="/security" label="Read about security" /></section>
    <Faq items={faqs} /><FinalCta />
  </PublicPage>;
}
