import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Breadcrumbs, FinalCta, PageIntro, PublicPage, TextCta } from "@/components/marketing/public-shell";
import { resourcePages } from "@/lib/marketing/content";
import { absoluteUrl, breadcrumbSchema, publicMetadata } from "@/lib/marketing/seo";

export function generateStaticParams() { return resourcePages.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const article = resourcePages.find((item) => item.slug === slug); return article ? publicMetadata({ title: `${article.title} | Inventman`, description: article.description, path: `/resources/${article.slug}` }) : {}; }
export default async function ResourceArticle({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const article = resourcePages.find((item) => item.slug === slug); if (!article) notFound(); const path = `/resources/${article.slug}`; return <PublicPage schema={[breadcrumbSchema([{ name: "Home", path: "/" }, { name: "Resources", path: "/resources" }, { name: article.title, path }]), { "@context": "https://schema.org", "@type": "Article", headline: article.title, description: article.description, datePublished: article.updated, dateModified: article.updated, author: { "@type": "Organization", name: "Inventman" }, publisher: { "@type": "Organization", name: "Inventman" }, mainEntityOfPage: absoluteUrl(path) }]}><div className="public-container"><Breadcrumbs items={[{ name: "Home", href: "/" }, { name: "Resources", href: "/resources" }, { name: article.title }]} /></div><PageIntro eyebrow={`Inventman guide · Updated ${article.updated}`} title={article.title} body={article.description} /><article className="section article-body">{article.sections.map(([heading, body]) => <section key={heading}><h2>{heading}</h2><p>{body}</p></section>)}<aside><h2>Put the guidance into practice</h2><p>See how Inventman supports the related workflow with connected operating records.</p><TextCta href={`/features/${article.relatedFeature}`} label="Explore the related feature" /></aside><p><Link href="/resources">← Back to all resources</Link></p></article><FinalCta /></PublicPage>; }
