import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Breadcrumbs, CheckList, Faq, FinalCta, PageIntro, PrimaryCta, PublicPage, RelatedFeatures, TextCta } from "@/components/marketing/public-shell";
import { industryPages } from "@/lib/marketing/content";
import { breadcrumbSchema, faqSchema, publicMetadata } from "@/lib/marketing/seo";

export function generateStaticParams() { return industryPages.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const page = industryPages.find((item) => item.slug === slug); return page ? publicMetadata({ title: page.title, description: page.description, path: `/industries/${page.slug}` }) : {}; }
export default async function IndustryPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const page = industryPages.find((item) => item.slug === slug); if (!page) notFound(); const crumbs = [{ name: "Home", path: "/" }, { name: "Industries", path: "/industries" }, { name: page.name, path: `/industries/${page.slug}` }]; return <PublicPage schema={[breadcrumbSchema(crumbs), faqSchema(page.faq)]}><div className="public-container"><Breadcrumbs items={[{ name: "Home", href: "/" }, { name: "Industries", href: "/industries" }, { name: page.name }]} /></div><PageIntro eyebrow={page.eyebrow} title={page.intro} body={page.description} actions={<><PrimaryCta /><TextCta href="/pricing" label="Compare plans" /></>} /><section className="section narrative-grid"><article><p className="eyebrow">Common operating pressure</p><h2>Where visibility breaks down</h2><p>{page.problem}</p></article><article className="accent-panel"><p className="eyebrow">A practical response</p><h2>Connect the work already happening.</h2><p>{page.answer}</p></article></section><section className="section workflow-section"><div className="section-heading"><p className="eyebrow">Relevant workflows</p><h2>Use Inventman across the operating cycle.</h2></div><ol>{page.workflows.map((workflow, index) => <li key={workflow}><span>{String(index + 1).padStart(2, "0")}</span><p>{workflow}</p></li>)}</ol></section><section className="section benefit-panel"><div><p className="eyebrow">Operational outcomes</p><h2>Build a more accountable routine.</h2></div><CheckList items={page.benefits} /></section><RelatedFeatures slugs={page.related} /><Faq items={page.faq} /><FinalCta title={`Bring ${page.name.toLowerCase()} onto one operating record.`} /></PublicPage>; }
