import { PageHeader } from "@/components/ui/page-header";
import { createSettlementAccount, createSettlementMethod, updateSettlementAccount, updateSettlementMethod } from "@/features/payments/actions";
import { getEffectivePermissions, requireOrganizationPermission } from "@/features/organizations/context";

export default async function PaymentSettingsPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const query = await searchParams;
  const { client, organization } = await requireOrganizationPermission("payments.accounts.view");
  const permissions = await getEffectivePermissions(organization.id);
  const canManage = permissions.has("payments.accounts.manage");
  const [{ data: accounts }, { data: methods }, { data: branches }] = await Promise.all([
    client.from("payment_accounts").select("id,account_code,name,account_type,currency,status,description,branches(name)").order("name"),
    client.from("payment_methods").select("id,code,name,method_type,requires_reference,allows_overpayment,requires_approval,status,payment_accounts(name)").order("name"),
    client.from("branches").select("id,name").eq("status", "active").order("name"),
  ]);
  if (!canManage) {
    return <div className="space-y-7"><PageHeader eyebrow="Administration / Payments" title="Settlement accounts & methods" description="View the active operational settlement configuration. Management permission is required to make changes." /><section className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border bg-surface p-5"><h2 className="font-semibold">Accounts</h2><div className="mt-3 space-y-2">{accounts?.map((account) => <div key={account.id} className="rounded-xl border p-3"><strong>{account.account_code} · {account.name}</strong><p className="text-sm text-subtle">{account.account_type} · {account.currency} · {account.status}</p></div>)}</div></div><div className="rounded-2xl border bg-surface p-5"><h2 className="font-semibold">Methods</h2><div className="mt-3 space-y-2">{methods?.map((method) => <div key={method.id} className="rounded-xl border p-3"><strong>{method.code} · {method.name}</strong><p className="text-sm text-subtle">{method.method_type} · {method.status}</p></div>)}</div></div></section></div>;
  }
  return <div className="space-y-7"><PageHeader eyebrow="Administration / Payments" title="Settlement accounts & methods" description="Configure operational cash, bank, card-clearing, and mobile-money settlement. These are not General Ledger accounts." />
    {query.error && <p className="rounded-xl border border-danger bg-danger/5 p-3 text-sm text-danger">{query.error}</p>}
    <section className="grid gap-6 xl:grid-cols-2"><form action={createSettlementAccount} className="rounded-2xl border bg-surface p-5"><h2 className="font-semibold">New settlement account</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><input required name="code" placeholder="Account code" className="rounded-xl border p-3"/><input required name="name" placeholder="Account name" className="rounded-xl border p-3"/><select name="type" className="rounded-xl border p-3">{["CASH","BANK","CARD_CLEARING","MOBILE_MONEY","OTHER_CLEARING"].map(x=><option key={x}>{x}</option>)}</select><input required name="currency" defaultValue={organization.currency_code} className="rounded-xl border p-3"/><select name="branchId" className="rounded-xl border p-3"><option value="">All branches</option>{branches?.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input name="description" placeholder="Description" className="rounded-xl border p-3"/></div><button className="mt-4 rounded-xl bg-ink px-4 py-3 text-sm font-semibold text-white">Create account</button></form>
    <form action={createSettlementMethod} className="rounded-2xl border bg-surface p-5"><h2 className="font-semibold">New payment method</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><input required name="code" placeholder="Method code" className="rounded-xl border p-3"/><input required name="name" placeholder="Method name" className="rounded-xl border p-3"/><select name="type" className="rounded-xl border p-3">{["CASH","BANK_TRANSFER","CARD","MOBILE_MONEY","CHEQUE","STORE_CREDIT","OTHER"].map(x=><option key={x}>{x}</option>)}</select><select required name="accountId" className="rounded-xl border p-3"><option value="">Default account</option>{accounts?.filter(x=>x.status==="ACTIVE").map(x=><option key={x.id} value={x.id}>{x.name} · {x.currency}</option>)}</select><select name="branchId" className="rounded-xl border p-3"><option value="">All branches</option>{branches?.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><label className="text-sm"><input type="checkbox" name="requiresReference"/> Requires reference</label><label className="text-sm"><input type="checkbox" name="allowsOverpayment" defaultChecked/> Allows overpayment</label><label className="text-sm"><input type="checkbox" name="requiresApproval"/> Requires approval</label></div><button className="mt-4 rounded-xl bg-ink px-4 py-3 text-sm font-semibold text-white">Create method</button></form></section>
    <section className="grid gap-6 xl:grid-cols-2"><div><h2 className="mb-3 text-lg font-semibold">Accounts</h2><div className="space-y-2">{accounts?.map(x=><form action={updateSettlementAccount.bind(null,x.id)} key={x.id} className="rounded-xl border p-4"><strong>{x.account_code} · {x.account_type} · {x.currency}</strong><div className="mt-3 grid gap-2 sm:grid-cols-2"><input aria-label={`Account name ${x.account_code}`} name="name" defaultValue={x.name} className="rounded border p-2"/><select aria-label={`Account status ${x.account_code}`} name="status" defaultValue={x.status} className="rounded border p-2"><option>ACTIVE</option><option>INACTIVE</option></select><input name="description" defaultValue={x.description??""} className="rounded border p-2"/><button className="rounded border p-2 text-sm font-semibold">Save</button></div><p className="mt-2 text-xs text-subtle">{x.branches?.name ?? "All branches"}</p></form>)}</div></div><div><h2 className="mb-3 text-lg font-semibold">Methods</h2><div className="space-y-2">{methods?.map(x=><form action={updateSettlementMethod.bind(null,x.id)} key={x.id} className="rounded-xl border p-4"><strong>{x.code} · {x.method_type} · {x.payment_accounts?.name}</strong><div className="mt-3 grid gap-2 sm:grid-cols-2"><input aria-label={`Method name ${x.code}`} name="name" defaultValue={x.name} className="rounded border p-2"/><select aria-label={`Method status ${x.code}`} name="status" defaultValue={x.status} className="rounded border p-2"><option>ACTIVE</option><option>INACTIVE</option></select><label className="text-sm"><input type="checkbox" name="requiresReference" defaultChecked={x.requires_reference}/> Reference required</label><label className="text-sm"><input type="checkbox" name="allowsOverpayment" defaultChecked={x.allows_overpayment}/> Overpayment</label><label className="text-sm"><input type="checkbox" name="requiresApproval" defaultChecked={x.requires_approval}/> Approval</label><button className="rounded border p-2 text-sm font-semibold">Save</button></div></form>)}</div></div></section>
  </div>;
}
