create or replace function public.next_procurement_number(target_organization_id uuid,target_prefix text)
returns text language sql security definer set search_path='' as $$ select public.next_inventory_number(target_organization_id,target_prefix) $$;

create or replace function public.create_supplier(target_organization_id uuid,target_code text,target_type text,target_legal_name text,target_trading_name text,target_email text,target_phone text,target_currency text,target_payment_terms text,target_notes text)
returns uuid language plpgsql security definer set search_path='' as $$ declare new_id uuid:=gen_random_uuid(); begin
 if not public.has_permission(target_organization_id,'suppliers.create') then raise exception using errcode='42501',message='PERMISSION_DENIED'; end if;
 insert into public.suppliers(id,organization_id,supplier_code,supplier_type,legal_name,trading_name,email,phone,default_currency,default_payment_terms,notes,created_by) values(new_id,target_organization_id,upper(trim(target_code)),target_type,trim(target_legal_name),nullif(trim(target_trading_name),''),nullif(trim(target_email),''),nullif(trim(target_phone),''),target_currency,nullif(trim(target_payment_terms),''),nullif(trim(target_notes),''),auth.uid());
 insert into public.audit_events(organization_id,actor_id,action,entity_type,entity_id) values(target_organization_id,auth.uid(),'supplier.created','supplier',new_id); return new_id;
end $$;

create or replace function public.add_supplier_product(target_organization_id uuid,target_supplier_id uuid,target_variant_id uuid,target_packaging_id uuid,target_supplier_sku text,target_description text,target_minimum numeric,target_multiple numeric,target_lead_days integer,target_preferred boolean)
returns uuid language plpgsql security definer set search_path='' as $$ declare new_id uuid:=gen_random_uuid(); begin
 if not public.has_permission(target_organization_id,'suppliers.update') then raise exception using errcode='42501',message='PERMISSION_DENIED'; end if;
 if not exists(select 1 from public.suppliers where organization_id=target_organization_id and id=target_supplier_id and status='ACTIVE') then raise exception using errcode='P0001',message='SUPPLIER_NOT_ACTIVE'; end if;
 if not exists(select 1 from public.product_variant_packaging where organization_id=target_organization_id and id=target_packaging_id and product_variant_id=target_variant_id and is_active) then raise exception using errcode='P0001',message='INVALID_PACKAGING'; end if;
 if target_preferred then update public.supplier_products set is_preferred=false where organization_id=target_organization_id and product_variant_id=target_variant_id; end if;
 insert into public.supplier_products(id,organization_id,supplier_id,product_variant_id,preferred_packaging_id,supplier_sku,supplier_description,minimum_order_quantity,order_multiple,lead_time_days,is_preferred) values(new_id,target_organization_id,target_supplier_id,target_variant_id,target_packaging_id,nullif(trim(target_supplier_sku),''),nullif(trim(target_description),''),target_minimum,target_multiple,target_lead_days,target_preferred); return new_id;
end $$;

create or replace function public.create_purchase_requisition(target_organization_id uuid,target_business_id uuid,target_branch_id uuid,target_required_by date,target_priority text,target_department text,target_justification text,target_lines jsonb)
returns uuid language plpgsql security definer set search_path='' as $$ declare new_id uuid:=gen_random_uuid(); number text; line jsonb; package record; begin
 if not public.has_permission(target_organization_id,'procurement.requisition_create') or not public.can_access_branch(target_organization_id,target_branch_id) then raise exception using errcode='42501',message='PERMISSION_DENIED'; end if;
 if jsonb_typeof(target_lines)<>'array' or jsonb_array_length(target_lines)=0 then raise exception using errcode='22023',message='INVALID_LINES'; end if;
 number:=public.next_procurement_number(target_organization_id,'REQ');
 insert into public.purchase_requisitions(id,organization_id,business_id,requisition_number,requesting_branch_id,requesting_user_id,department,required_by_date,priority,justification) values(new_id,target_organization_id,target_business_id,number,target_branch_id,auth.uid(),nullif(trim(target_department),''),target_required_by,target_priority,nullif(trim(target_justification),''));
 for line in select value from jsonb_array_elements(target_lines) loop
  select id,product_variant_id,conversion_to_base into package from public.product_variant_packaging where organization_id=target_organization_id and id=(line->>'packaging_id')::uuid and product_variant_id=(line->>'product_variant_id')::uuid and is_active;
  if not found or (line->>'quantity')::numeric<=0 then raise exception using errcode='P0001',message='INVALID_REQUISITION_LINE'; end if;
  insert into public.purchase_requisition_lines(organization_id,requisition_id,product_variant_id,packaging_id,requested_quantity,conversion_snapshot,requested_base_quantity,estimated_unit_cost,notes) values(target_organization_id,new_id,package.product_variant_id,package.id,(line->>'quantity')::numeric,package.conversion_to_base,round((line->>'quantity')::numeric*package.conversion_to_base,6),nullif(line->>'estimated_unit_cost','')::numeric,nullif(line->>'notes',''));
 end loop;
 insert into public.procurement_activity(organization_id,document_type,document_id,action,actor_id) values(target_organization_id,'REQUISITION',new_id,'CREATED',auth.uid()); return new_id;
end $$;

create or replace function public.submit_purchase_requisition(target_organization_id uuid,target_requisition_id uuid,target_idempotency_key uuid)
returns uuid language plpgsql security definer set search_path='' as $$ declare doc public.purchase_requisitions%rowtype; req_id uuid:=gen_random_uuid(); policy public.approval_policies%rowtype; amount numeric; begin
 select * into doc from public.purchase_requisitions where organization_id=target_organization_id and id=target_requisition_id for update;
 if not found or not public.has_permission(target_organization_id,'procurement.requisition_submit') or not public.can_access_branch(target_organization_id,doc.requesting_branch_id) then raise exception using errcode='42501',message='PERMISSION_DENIED'; end if;
 if doc.status in ('SUBMITTED','PENDING_APPROVAL','APPROVED') then return (select id from public.approval_requests where organization_id=target_organization_id and document_type='REQUISITION' and document_id=doc.id order by submitted_at desc limit 1); end if;
 if doc.status<>'DRAFT' then raise exception using errcode='P0001',message='INVALID_STATE_TRANSITION'; end if;
 select coalesce(sum(requested_base_quantity*coalesce(estimated_unit_cost,0)),0) into amount from public.purchase_requisition_lines where requisition_id=doc.id;
 select * into policy from public.approval_policies where organization_id=target_organization_id and document_type='REQUISITION' and is_active and (branch_id is null or branch_id=doc.requesting_branch_id) and minimum_amount<=amount order by minimum_amount desc limit 1;
 insert into public.approval_requests(id,organization_id,policy_id,document_type,document_id,branch_id,amount,currency,requester_id,document_hash) values(req_id,target_organization_id,policy.id,'REQUISITION',doc.id,doc.requesting_branch_id,amount,(select currency_code from public.organizations where id=target_organization_id),auth.uid(),encode(extensions.digest(convert_to(jsonb_build_object('id',doc.id,'amount',amount,'key',target_idempotency_key)::text,'UTF8'),'sha256'),'hex'));
 update public.purchase_requisitions set status='PENDING_APPROVAL',submitted_at=now(),updated_at=now() where id=doc.id;
 insert into public.procurement_activity(organization_id,document_type,document_id,action,actor_id) values(target_organization_id,'REQUISITION',doc.id,'SUBMITTED',auth.uid()); return req_id;
end $$;

create or replace function public.act_on_approval(target_organization_id uuid,target_approval_request_id uuid,target_action text,target_comments text)
returns text language plpgsql security definer set search_path='' as $$ declare req public.approval_requests%rowtype; policy public.approval_policies%rowtype; step public.approval_steps%rowtype; action_count integer; next_exists boolean; begin
 select * into req from public.approval_requests where organization_id=target_organization_id and id=target_approval_request_id for update;
 if not found or req.status<>'PENDING' or not public.can_access_branch(target_organization_id,req.branch_id) then raise exception using errcode='42501',message='APPROVAL_NOT_AVAILABLE'; end if;
 select * into policy from public.approval_policies where id=req.policy_id; select * into step from public.approval_steps where policy_id=req.policy_id and step_order=req.current_step;
 if found and not public.has_permission(target_organization_id,step.permission_code) then raise exception using errcode='42501',message='UNAUTHORIZED_APPROVAL'; end if;
 if policy.prohibit_self_approval and req.requester_id=auth.uid() then raise exception using errcode='42501',message='SELF_APPROVAL_DENIED'; end if;
 if target_action not in ('APPROVE','REJECT','RETURN_FOR_CHANGES','CANCEL') then raise exception using errcode='22023',message='INVALID_APPROVAL_ACTION'; end if;
 insert into public.approval_actions(organization_id,approval_request_id,step_order,actor_id,action,comments) values(target_organization_id,req.id,req.current_step,auth.uid(),target_action,nullif(trim(target_comments),''));
 if target_action='APPROVE' then
  select count(*) into action_count from public.approval_actions where approval_request_id=req.id and step_order=req.current_step and action='APPROVE';
  select exists(select 1 from public.approval_steps where policy_id=req.policy_id and step_order>req.current_step) into next_exists;
  if action_count>=coalesce(step.approvals_required,1) and next_exists then update public.approval_requests set current_step=current_step+1 where id=req.id;
  elsif action_count>=coalesce(step.approvals_required,1) then update public.approval_requests set status='APPROVED',finalized_at=now() where id=req.id; if req.document_type='REQUISITION' then update public.purchase_requisitions set status='APPROVED',approved_at=now(),updated_at=now() where id=req.document_id; elsif req.document_type='PURCHASE_ORDER' then update public.purchase_orders set status='APPROVED',approved_by=auth.uid(),approved_at=now(),updated_at=now() where id=req.document_id; end if; end if;
 else update public.approval_requests set status=case target_action when 'REJECT' then 'REJECTED' when 'RETURN_FOR_CHANGES' then 'RETURNED' else 'CANCELLED' end,finalized_at=now() where id=req.id; if req.document_type='REQUISITION' then update public.purchase_requisitions set status=case when target_action='REJECT' then 'REJECTED' else 'DRAFT' end,rejected_at=case when target_action='REJECT' then now() end where id=req.document_id; elsif req.document_type='PURCHASE_ORDER' then update public.purchase_orders set status=case when target_action='REJECT' then 'CANCELLED' else 'DRAFT' end where id=req.document_id; end if;
 end if;
 insert into public.procurement_activity(organization_id,document_type,document_id,action,actor_id,details) values(target_organization_id,req.document_type,req.document_id,target_action,auth.uid(),jsonb_build_object('comments',target_comments)); return target_action;
end $$;

create or replace function public.create_purchase_order(target_organization_id uuid,target_business_id uuid,target_supplier_id uuid,target_branch_id uuid,target_warehouse_id uuid,target_location_id uuid,target_order_date date,target_expected_date date,target_currency text,target_exchange_rate numeric,target_payment_terms text,target_notes text,target_lines jsonb)
returns uuid language plpgsql security definer set search_path='' as $$ declare new_id uuid:=gen_random_uuid(); number text; supplier public.suppliers%rowtype; line jsonb; package record; variant record; subtotal numeric:=0; line_total numeric; base_currency text; begin
 if not public.has_permission(target_organization_id,'procurement.po_create') or not public.can_access_branch(target_organization_id,target_branch_id) then raise exception using errcode='42501',message='PERMISSION_DENIED'; end if;
 select * into supplier from public.suppliers where organization_id=target_organization_id and id=target_supplier_id and status='ACTIVE'; if not found then raise exception using errcode='P0001',message='SUPPLIER_NOT_ACTIVE'; end if;
 if not exists(select 1 from public.storage_locations l where l.organization_id=target_organization_id and l.id=target_location_id and l.warehouse_id=target_warehouse_id and l.branch_id=target_branch_id and l.is_active) then raise exception using errcode='P0001',message='INVALID_DESTINATION'; end if;
 select currency_code into base_currency from public.organizations where id=target_organization_id; number:=public.next_procurement_number(target_organization_id,'PO');
 for line in select value from jsonb_array_elements(target_lines) loop subtotal:=subtotal+round((line->>'quantity')::numeric*(line->>'unit_price')::numeric-coalesce(nullif(line->>'discount','')::numeric,0)+coalesce(nullif(line->>'tax','')::numeric,0),4); end loop;
 insert into public.purchase_orders(id,organization_id,business_id,purchase_order_number,supplier_id,branch_id,receiving_warehouse_id,receiving_location_id,order_date,expected_delivery_date,currency,exchange_rate,base_currency,subtotal,total,base_currency_total,payment_terms,supplier_name_snapshot,supplier_code_snapshot,supplier_terms_snapshot,notes,created_by) values(new_id,target_organization_id,target_business_id,number,target_supplier_id,target_branch_id,target_warehouse_id,target_location_id,target_order_date,target_expected_date,target_currency,target_exchange_rate,base_currency,subtotal,subtotal,round(subtotal*target_exchange_rate,4),target_payment_terms,supplier.legal_name,supplier.supplier_code,supplier.default_payment_terms,target_notes,auth.uid());
 for line in select value from jsonb_array_elements(target_lines) loop select p.id,p.product_variant_id,p.conversion_to_base,v.name into package from public.product_variant_packaging p join public.product_variants v on v.id=p.product_variant_id and v.organization_id=p.organization_id where p.organization_id=target_organization_id and p.id=(line->>'packaging_id')::uuid and p.product_variant_id=(line->>'product_variant_id')::uuid and p.is_active; if not found then raise exception using errcode='P0001',message='INVALID_PACKAGING'; end if; line_total:=round((line->>'quantity')::numeric*(line->>'unit_price')::numeric-coalesce(nullif(line->>'discount','')::numeric,0)+coalesce(nullif(line->>'tax','')::numeric,0),4); insert into public.purchase_order_lines(organization_id,purchase_order_id,product_variant_id,packaging_id,product_description_snapshot,supplier_item_code_snapshot,ordered_quantity,conversion_snapshot,ordered_base_quantity,unit_price,discount,tax,line_total) values(target_organization_id,new_id,package.product_variant_id,package.id,package.name,line->>'supplier_sku',(line->>'quantity')::numeric,package.conversion_to_base,round((line->>'quantity')::numeric*package.conversion_to_base,6),(line->>'unit_price')::numeric,coalesce(nullif(line->>'discount','')::numeric,0),coalesce(nullif(line->>'tax','')::numeric,0),line_total); end loop;
 insert into public.procurement_activity(organization_id,document_type,document_id,action,actor_id) values(target_organization_id,'PURCHASE_ORDER',new_id,'CREATED',auth.uid()); return new_id;
end $$;

create or replace function public.approve_purchase_order(target_organization_id uuid,target_purchase_order_id uuid,target_idempotency_key uuid)
returns uuid language plpgsql security definer set search_path='' as $$ declare doc public.purchase_orders%rowtype; req uuid:=gen_random_uuid(); begin
 select * into doc from public.purchase_orders where organization_id=target_organization_id and id=target_purchase_order_id for update;
 if not found or not public.has_permission(target_organization_id,'procurement.po_approve') or not public.can_access_branch(target_organization_id,doc.branch_id) then raise exception using errcode='42501',message='PERMISSION_DENIED'; end if;
 if doc.status='APPROVED' then return doc.id; end if; if doc.status not in ('DRAFT','PENDING_APPROVAL') then raise exception using errcode='P0001',message='INVALID_STATE_TRANSITION'; end if;
 update public.purchase_orders set status='APPROVED',approved_by=auth.uid(),approved_at=now(),updated_at=now() where id=doc.id;
 insert into public.procurement_activity(organization_id,document_type,document_id,action,actor_id,details) values(target_organization_id,'PURCHASE_ORDER',doc.id,'APPROVED',auth.uid(),jsonb_build_object('idempotency_key',target_idempotency_key)); return doc.id;
end $$;

create or replace function public.post_goods_receipt(target_organization_id uuid,target_purchase_order_id uuid,target_supplier_delivery_note text,target_received_at timestamptz,target_notes text,target_idempotency_key uuid,target_allow_override boolean,target_override_reason text,target_lines jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$ declare po public.purchase_orders%rowtype; settings public.procurement_settings%rowtype; existing public.goods_receipts%rowtype; grn_id uuid:=gen_random_uuid(); grn_number text; line jsonb; po_line public.purchase_order_lines%rowtype; package record; delivered numeric; accepted numeric; rejected numeric; accepted_base numeric; allowed numeric; ledger_lines jsonb:='[]'::jsonb; inventory_result jsonb; all_received boolean; unit_cost_base numeric; begin
 select * into existing from public.goods_receipts where organization_id=target_organization_id and idempotency_key=target_idempotency_key; if found then return jsonb_build_object('goods_receipt_id',existing.id,'grn_number',existing.grn_number,'inventory_transaction_id',existing.inventory_transaction_id,'replayed',true); end if;
 select * into po from public.purchase_orders where organization_id=target_organization_id and id=target_purchase_order_id for update; if not found or po.status not in ('APPROVED','SENT','PARTIALLY_RECEIVED') then raise exception using errcode='P0001',message='PO_NOT_RECEIVABLE'; end if;
 if not public.has_permission(target_organization_id,'procurement.receipt_post') or not public.can_access_branch(target_organization_id,po.branch_id) then raise exception using errcode='42501',message='PERMISSION_DENIED'; end if;
 select * into settings from public.procurement_settings where organization_id=target_organization_id; grn_number:=public.next_procurement_number(target_organization_id,'GRN');
 insert into public.goods_receipts(id,organization_id,business_id,grn_number,purchase_order_id,supplier_id,branch_id,warehouse_id,storage_location_id,supplier_delivery_note,received_at,received_by,status,notes,idempotency_key) values(grn_id,target_organization_id,po.business_id,grn_number,po.id,po.supplier_id,po.branch_id,po.receiving_warehouse_id,po.receiving_location_id,nullif(trim(target_supplier_delivery_note),''),target_received_at,auth.uid(),'INSPECTED',nullif(trim(target_notes),''),target_idempotency_key);
 for line in select value from jsonb_array_elements(target_lines) loop
  select * into po_line from public.purchase_order_lines where organization_id=target_organization_id and purchase_order_id=po.id and id=(line->>'purchase_order_line_id')::uuid for update; if not found then raise exception using errcode='P0001',message='INVALID_PO_LINE'; end if;
  delivered:=(line->>'delivered_quantity')::numeric; accepted:=(line->>'accepted_quantity')::numeric; rejected:=coalesce(nullif(line->>'rejected_quantity','')::numeric,0); if delivered<0 or accepted<0 or rejected<0 or accepted+rejected>delivered then raise exception using errcode='22023',message='INVALID_RECEIPT_QUANTITY'; end if;
  accepted_base:=round(accepted*po_line.conversion_snapshot,6); allowed:=po_line.ordered_base_quantity-po_line.accepted_base_quantity;
  if settings.over_delivery_policy='ALLOW_WITH_TOLERANCE' then allowed:=allowed+round(po_line.ordered_base_quantity*settings.over_delivery_tolerance_percent/100,6); end if;
  if accepted_base>allowed and not(settings.over_delivery_policy='AUTHORIZED_OVERRIDE' and target_allow_override and public.has_permission(target_organization_id,'procurement.receipt_override') and nullif(trim(target_override_reason),'') is not null) then raise exception using errcode='P0001',message='OVER_RECEIPT_NOT_ALLOWED'; end if;
  unit_cost_base:=round((po_line.unit_price*po.exchange_rate)/po_line.conversion_snapshot,8);
  insert into public.goods_receipt_lines(organization_id,goods_receipt_id,purchase_order_line_id,product_variant_id,packaging_id,ordered_quantity_snapshot,previously_accepted_base_quantity,delivered_quantity,accepted_quantity,rejected_quantity,damaged_quantity,conversion_snapshot,accepted_base_quantity,inspection_status,rejection_reason,damage_reason,notes,unit_purchase_cost_base,inventory_unit_cost_base) values(target_organization_id,grn_id,po_line.id,po_line.product_variant_id,po_line.packaging_id,po_line.ordered_quantity,po_line.accepted_base_quantity,delivered,accepted,rejected,coalesce(nullif(line->>'damaged_quantity','')::numeric,0),po_line.conversion_snapshot,accepted_base,case when accepted=0 then 'REJECTED' when rejected>0 then 'PARTIALLY_ACCEPTED' else 'ACCEPTED' end,nullif(line->>'rejection_reason',''),nullif(line->>'damage_reason',''),nullif(line->>'notes',''),unit_cost_base,unit_cost_base);
  update public.purchase_order_lines set accepted_base_quantity=accepted_base_quantity+accepted_base,rejected_base_quantity=rejected_base_quantity+round(rejected*conversion_snapshot,6) where id=po_line.id;
  if accepted>0 then ledger_lines:=ledger_lines||jsonb_build_array(jsonb_build_object('product_variant_id',po_line.product_variant_id,'storage_location_id',po.receiving_location_id,'packaging_id',po_line.packaging_id,'quantity',accepted,'unit_cost',unit_cost_base)); end if;
 end loop;
 if jsonb_array_length(ledger_lines)=0 then raise exception using errcode='P0001',message='NO_ACCEPTED_GOODS'; end if;
 inventory_result:=public.post_inventory_transaction(target_organization_id,po.business_id,'PURCHASE_RECEIPT',target_received_at,null,coalesce(nullif(trim(target_notes),''),'Goods receipt '||grn_number),target_supplier_delivery_note,target_idempotency_key,ledger_lines,'PURCHASE_RECEIPT',grn_id,null,null,null,'WEB',false);
 update public.goods_receipts set status='POSTED',posted_at=now(),inventory_transaction_id=(inventory_result->>'transaction_id')::uuid where id=grn_id;
 select not exists(select 1 from public.purchase_order_lines where purchase_order_id=po.id and accepted_base_quantity<ordered_base_quantity) into all_received; update public.purchase_orders set status=case when all_received then 'FULLY_RECEIVED' else 'PARTIALLY_RECEIVED' end,updated_at=now() where id=po.id;
 insert into public.procurement_activity(organization_id,document_type,document_id,action,actor_id,details) values(target_organization_id,'GOODS_RECEIPT',grn_id,'POSTED',auth.uid(),jsonb_build_object('inventory_transaction_id',inventory_result->>'transaction_id','override_reason',target_override_reason)); return jsonb_build_object('goods_receipt_id',grn_id,'grn_number',grn_number,'inventory_transaction_id',inventory_result->>'transaction_id','replayed',false);
end $$;

create or replace function public.post_purchase_return(target_organization_id uuid,target_business_id uuid,target_supplier_id uuid,target_po_id uuid,target_grn_id uuid,target_branch_id uuid,target_location_id uuid,target_reason text,target_notes text,target_idempotency_key uuid,target_lines jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$ declare existing public.purchase_returns%rowtype; return_id uuid:=gen_random_uuid(); number text; line jsonb; package record; ledger_lines jsonb:='[]'::jsonb; result jsonb; begin
 select * into existing from public.purchase_returns where organization_id=target_organization_id and idempotency_key=target_idempotency_key; if found then return jsonb_build_object('purchase_return_id',existing.id,'return_number',existing.return_number,'inventory_transaction_id',existing.inventory_transaction_id,'replayed',true); end if;
 if not public.has_permission(target_organization_id,'procurement.return_post') or not public.can_access_branch(target_organization_id,target_branch_id) then raise exception using errcode='42501',message='PERMISSION_DENIED'; end if;
 number:=public.next_procurement_number(target_organization_id,'PRET'); insert into public.purchase_returns(id,organization_id,business_id,return_number,supplier_id,purchase_order_id,goods_receipt_id,branch_id,storage_location_id,return_date,reason,notes,status,idempotency_key,created_by) values(return_id,target_organization_id,target_business_id,number,target_supplier_id,target_po_id,target_grn_id,target_branch_id,target_location_id,now(),target_reason,nullif(trim(target_notes),''),'APPROVED',target_idempotency_key,auth.uid());
 for line in select value from jsonb_array_elements(target_lines) loop select id,product_variant_id,conversion_to_base into package from public.product_variant_packaging where organization_id=target_organization_id and id=(line->>'packaging_id')::uuid and product_variant_id=(line->>'product_variant_id')::uuid; if not found then raise exception using errcode='P0001',message='INVALID_PACKAGING'; end if; insert into public.purchase_return_lines(organization_id,purchase_return_id,goods_receipt_line_id,product_variant_id,packaging_id,quantity,conversion_snapshot,base_quantity,unit_cost_base) values(target_organization_id,return_id,nullif(line->>'goods_receipt_line_id','')::uuid,package.product_variant_id,package.id,(line->>'quantity')::numeric,package.conversion_to_base,round((line->>'quantity')::numeric*package.conversion_to_base,6),(line->>'unit_cost_base')::numeric); ledger_lines:=ledger_lines||jsonb_build_array(jsonb_build_object('product_variant_id',package.product_variant_id,'storage_location_id',target_location_id,'packaging_id',package.id,'quantity',(line->>'quantity')::numeric)); end loop;
 result:=public.post_inventory_transaction(target_organization_id,target_business_id,'PURCHASE_RETURN',now(),null,coalesce(nullif(trim(target_notes),''),'Purchase return '||number),number,target_idempotency_key,ledger_lines,'PURCHASE_RETURN',return_id,null,null,null,'WEB',false); update public.purchase_returns set status='POSTED',posted_at=now(),inventory_transaction_id=(result->>'transaction_id')::uuid where id=return_id; insert into public.procurement_activity(organization_id,document_type,document_id,action,actor_id) values(target_organization_id,'PURCHASE_RETURN',return_id,'POSTED',auth.uid()); return jsonb_build_object('purchase_return_id',return_id,'return_number',number,'inventory_transaction_id',result->>'transaction_id','replayed',false);
end $$;

create or replace function public.record_supplier_invoice(target_organization_id uuid,target_supplier_id uuid,target_invoice_number text,target_invoice_date date,target_due_date date,target_currency text,target_exchange_rate numeric,target_subtotal numeric,target_discount numeric,target_tax numeric,target_freight numeric,target_total numeric,target_notes text,target_po_ids uuid[],target_grn_ids uuid[])
returns uuid language plpgsql security definer set search_path='' as $$ declare new_id uuid:=gen_random_uuid(); base_currency text; po_id uuid; grn_id uuid; matched_total numeric; match text; begin
 if not public.has_permission(target_organization_id,'procurement.invoice_create') then raise exception using errcode='42501',message='PERMISSION_DENIED'; end if; if not exists(select 1 from public.suppliers where organization_id=target_organization_id and id=target_supplier_id and status<>'ARCHIVED') then raise exception using errcode='P0001',message='INVALID_SUPPLIER'; end if;
 select currency_code into base_currency from public.organizations where id=target_organization_id; if round(target_subtotal-target_discount+target_tax+target_freight,4)<>round(target_total,4) then raise exception using errcode='P0001',message='INVOICE_TOTAL_MISMATCH'; end if;
 select coalesce(sum(total),0) into matched_total from public.purchase_orders where organization_id=target_organization_id and id=any(coalesce(target_po_ids,'{}'::uuid[])); match:=case when abs(matched_total-target_total)<=0.01 then 'MATCHED' else 'TOTAL_VARIANCE' end;
 insert into public.supplier_invoices(id,organization_id,supplier_id,invoice_number,invoice_date,due_date,currency,exchange_rate,base_currency,subtotal,discount,tax,freight_charges,total,base_currency_total,status,match_status,notes,created_by) values(new_id,target_organization_id,target_supplier_id,trim(target_invoice_number),target_invoice_date,target_due_date,target_currency,target_exchange_rate,base_currency,target_subtotal,target_discount,target_tax,target_freight,target_total,round(target_total*target_exchange_rate,4),'REVIEW',match,nullif(trim(target_notes),''),auth.uid());
 foreach po_id in array coalesce(target_po_ids,'{}'::uuid[]) loop if not exists(select 1 from public.purchase_orders where organization_id=target_organization_id and id=po_id and supplier_id=target_supplier_id) then raise exception using errcode='P0001',message='CROSS_TENANT_REFERENCE'; end if; end loop;
 foreach grn_id in array coalesce(target_grn_ids,'{}'::uuid[]) loop if not exists(select 1 from public.goods_receipts where organization_id=target_organization_id and id=grn_id and supplier_id=target_supplier_id) then raise exception using errcode='P0001',message='CROSS_TENANT_REFERENCE'; end if; end loop;
 insert into public.procurement_activity(organization_id,document_type,document_id,action,actor_id,details) values(target_organization_id,'SUPPLIER_INVOICE',new_id,'RECORDED',auth.uid(),jsonb_build_object('match_status',match)); return new_id;
end $$;

do $$ declare f record; begin for f in select p.oid::regprocedure signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('next_procurement_number','create_supplier','add_supplier_product','create_purchase_requisition','submit_purchase_requisition','act_on_approval','create_purchase_order','approve_purchase_order','post_goods_receipt','post_purchase_return','record_supplier_invoice') loop execute format('revoke all on function %s from public,anon',f.signature); execute format('grant execute on function %s to authenticated',f.signature); end loop; end $$;
