create or replace function public.record_supplier_invoice(target_organization_id uuid,target_supplier_id uuid,target_invoice_number text,target_invoice_date date,target_due_date date,target_currency text,target_exchange_rate numeric,target_subtotal numeric,target_discount numeric,target_tax numeric,target_freight numeric,target_total numeric,target_notes text,target_po_ids uuid[],target_grn_ids uuid[])
returns uuid language plpgsql security definer set search_path='' as $$ declare new_id uuid:=gen_random_uuid(); base_currency text; po_id uuid; grn_id uuid; matched_total numeric; match text; begin
 if not public.has_permission(target_organization_id,'procurement.invoice_create') then raise exception using errcode='42501',message='PERMISSION_DENIED'; end if; if not exists(select 1 from public.suppliers where organization_id=target_organization_id and id=target_supplier_id and status<>'ARCHIVED') then raise exception using errcode='P0001',message='INVALID_SUPPLIER'; end if;
 select currency_code into base_currency from public.organizations where id=target_organization_id; if round(target_subtotal-target_discount+target_tax+target_freight,4)<>round(target_total,4) then raise exception using errcode='P0001',message='INVOICE_TOTAL_MISMATCH'; end if;
 select coalesce(sum(total),0) into matched_total from public.purchase_orders where organization_id=target_organization_id and id=any(coalesce(target_po_ids,'{}'::uuid[])); match:=case when abs(matched_total-target_total)<=0.01 then 'MATCHED' else 'TOTAL_VARIANCE' end;
 insert into public.supplier_invoices(id,organization_id,supplier_id,invoice_number,invoice_date,due_date,currency,exchange_rate,base_currency,subtotal,discount,tax,freight_charges,total,base_currency_total,status,match_status,notes,created_by) values(new_id,target_organization_id,target_supplier_id,trim(target_invoice_number),target_invoice_date,target_due_date,target_currency,target_exchange_rate,base_currency,target_subtotal,target_discount,target_tax,target_freight,target_total,round(target_total*target_exchange_rate,4),'REVIEW',match,nullif(trim(target_notes),''),auth.uid());
 foreach po_id in array coalesce(target_po_ids,'{}'::uuid[]) loop if not exists(select 1 from public.purchase_orders where organization_id=target_organization_id and id=po_id and supplier_id=target_supplier_id) then raise exception using errcode='P0001',message='CROSS_TENANT_REFERENCE'; end if; end loop;
 foreach grn_id in array coalesce(target_grn_ids,'{}'::uuid[]) loop if not exists(select 1 from public.goods_receipts where organization_id=target_organization_id and id=grn_id and supplier_id=target_supplier_id) then raise exception using errcode='P0001',message='CROSS_TENANT_REFERENCE'; end if; end loop;
 foreach po_id in array coalesce(target_po_ids,'{}'::uuid[]) loop foreach grn_id in array coalesce(target_grn_ids,'{}'::uuid[]) loop if not exists(select 1 from public.goods_receipts where organization_id=target_organization_id and id=grn_id and purchase_order_id=po_id) then raise exception using errcode='P0001',message='THREE_WAY_REFERENCE_MISMATCH'; end if; insert into public.supplier_invoice_links(organization_id,supplier_invoice_id,purchase_order_id,goods_receipt_id) values(target_organization_id,new_id,po_id,grn_id); end loop; end loop;
 insert into public.procurement_activity(organization_id,document_type,document_id,action,actor_id,details) values(target_organization_id,'SUPPLIER_INVOICE',new_id,'RECORDED',auth.uid(),jsonb_build_object('match_status',match)); return new_id;
end $$;
revoke all on function public.record_supplier_invoice(uuid,uuid,text,date,date,text,numeric,numeric,numeric,numeric,numeric,numeric,text,uuid[],uuid[]) from public,anon;
grant execute on function public.record_supplier_invoice(uuid,uuid,text,date,date,text,numeric,numeric,numeric,numeric,numeric,numeric,text,uuid[],uuid[]) to authenticated;
