insert into public.permissions(code,description) values
('customers.view','View customers'),('customers.create','Create customers'),('customers.update','Update customers'),('customers.archive','Archive customers'),('customers.credit_manage','Manage customer credit'),
('sales.quotation_view','View sales quotations'),('sales.quotation_create','Create sales quotations'),('sales.quotation_update','Update sales quotations'),('sales.quotation_submit','Submit sales quotations'),('sales.quotation_approve','Approve sales quotations'),
('sales.order_view','View sales orders'),('sales.order_create','Create sales orders'),('sales.order_update','Update sales orders'),('sales.order_confirm','Confirm sales orders'),('sales.order_cancel','Cancel sales orders'),
('sales.fulfilment_view','View fulfilments'),('sales.fulfilment_create','Create fulfilments'),('sales.fulfilment_post','Post fulfilments'),('sales.invoice_view','View customer invoices'),('sales.invoice_create','Create customer invoices'),('sales.invoice_issue','Issue customer invoices'),('sales.invoice_void','Void customer invoices'),
('sales.return_view','View sales returns'),('sales.return_create','Create sales returns'),('sales.return_approve','Approve sales returns'),('sales.return_receive','Inspect sales returns'),('sales.return_post','Post sales returns'),
('sales.credit_note_view','View credit notes'),('sales.credit_note_create','Create credit notes'),('sales.credit_note_approve','Approve credit notes'),('sales.discount_override','Override sales discount'),('sales.price_override','Override minimum price'),('sales.credit_override','Override customer credit limit'),
('receivables.view','View receivables'),('receivables.aging_view','View receivables aging'),('receivables.statement_view','View customer statements'),('sales.reports_view','View sales reports') on conflict(code) do update set description=excluded.description;
insert into public.role_permissions(organization_id,role_id,permission_id) select r.organization_id,r.id,p.id from public.roles r cross join public.permissions p where r.is_system and r.name in('Owner','Administrator') and(p.code like 'customers.%' or p.code like 'sales.%' or p.code like 'receivables.%') on conflict do nothing;
insert into public.sales_settings(organization_id) select id from public.organizations on conflict do nothing;
insert into public.sales_return_reasons(organization_id,code,name,requires_notes,created_by) select o.id,x.code,x.name,x.notes,o.created_by from public.organizations o cross join(values('DEFECTIVE','Defective',true),('WRONG_ITEM','Wrong item',true),('DAMAGED','Damaged',true),('CHANGED_MIND','Customer changed mind',false),('QUALITY','Quality issue',true),('WARRANTY','Warranty',true),('OTHER','Other',true))x(code,name,notes) on conflict do nothing;
create or replace function public.seed_sales_organization() returns trigger language plpgsql security definer set search_path='' as $$ begin insert into public.sales_settings(organization_id) values(new.id);insert into public.sales_return_reasons(organization_id,code,name,requires_notes,created_by) values(new.id,'DEFECTIVE','Defective',true,new.created_by),(new.id,'WRONG_ITEM','Wrong item',true,new.created_by),(new.id,'DAMAGED','Damaged',true,new.created_by),(new.id,'OTHER','Other',true,new.created_by);return new;end $$;
create trigger seed_sales_after_organization after insert on public.organizations for each row execute function public.seed_sales_organization();revoke execute on function public.seed_sales_organization() from public,anon,authenticated;
do $$declare t text;begin foreach t in array array['sales_settings','customers','customer_contacts','customer_addresses','customer_documents','sales_quotations','sales_quotation_lines','sales_orders','sales_order_lines','sales_fulfillments','sales_fulfillment_lines','customer_invoices','customer_invoice_lines','customer_invoice_fulfillments','sales_return_reasons','sales_returns','sales_return_lines','customer_credit_notes','sales_activity'] loop execute format('alter table public.%I enable row level security',t);execute format('alter table public.%I force row level security',t);execute format('revoke all on public.%I from anon,authenticated',t);execute format('grant select on public.%I to authenticated',t);end loop;end$$;grant select on public.customer_receivables to authenticated;
create policy customers_read on public.customers for select to authenticated using(public.has_permission(organization_id,'customers.view'));create policy contacts_read on public.customer_contacts for select to authenticated using(public.has_permission(organization_id,'customers.view'));create policy addresses_read on public.customer_addresses for select to authenticated using(public.has_permission(organization_id,'customers.view'));create policy customer_documents_read on public.customer_documents for select to authenticated using(public.has_permission(organization_id,'customers.view'));create policy sales_settings_read on public.sales_settings for select to authenticated using(public.has_permission(organization_id,'sales.order_view'));create policy return_reasons_read on public.sales_return_reasons for select to authenticated using(public.has_permission(organization_id,'sales.return_view'));
create policy quotations_read on public.sales_quotations for select to authenticated using(public.has_permission(organization_id,'sales.quotation_view') and public.can_access_branch(organization_id,branch_id));create policy quotation_lines_read on public.sales_quotation_lines for select to authenticated using(exists(select 1 from public.sales_quotations q where q.id=quotation_id and q.organization_id=organization_id and public.can_access_branch(organization_id,q.branch_id)));
create policy orders_read on public.sales_orders for select to authenticated using(public.has_permission(organization_id,'sales.order_view') and public.can_access_branch(organization_id,branch_id));create policy order_lines_read on public.sales_order_lines for select to authenticated using(exists(select 1 from public.sales_orders s where s.id=sales_order_id and s.organization_id=organization_id and public.can_access_branch(organization_id,s.branch_id)));
create policy fulfillments_read on public.sales_fulfillments for select to authenticated using(public.has_permission(organization_id,'sales.fulfilment_view') and public.can_access_branch(organization_id,branch_id));create policy fulfillment_lines_read on public.sales_fulfillment_lines for select to authenticated using(exists(select 1 from public.sales_fulfillments f where f.id=fulfilment_id and f.organization_id=organization_id and public.can_access_branch(organization_id,f.branch_id)));
create policy invoices_read on public.customer_invoices for select to authenticated using(public.has_permission(organization_id,'sales.invoice_view') and public.can_access_branch(organization_id,branch_id));create policy returns_read on public.sales_returns for select to authenticated using(public.has_permission(organization_id,'sales.return_view') and public.can_access_branch(organization_id,branch_id));create policy credits_read on public.customer_credit_notes for select to authenticated using(public.has_permission(organization_id,'sales.credit_note_view') and public.can_access_branch(organization_id,branch_id));create policy sales_activity_read on public.sales_activity for select to authenticated using(public.has_permission(organization_id,'sales.reports_view'));

alter table public.sales_return_cost_allocations enable row level security;alter table public.sales_return_cost_allocations force row level security;revoke all on public.sales_return_cost_allocations from anon,authenticated;grant select on public.sales_return_cost_allocations to authenticated;
create policy invoice_lines_read on public.customer_invoice_lines for select to authenticated using(exists(select 1 from public.customer_invoices i where i.organization_id=customer_invoice_lines.organization_id and i.id=customer_invoice_lines.invoice_id and public.has_permission(i.organization_id,'sales.invoice_view') and public.can_access_branch(i.organization_id,i.branch_id)));
create policy invoice_fulfillments_read on public.customer_invoice_fulfillments for select to authenticated using(exists(select 1 from public.customer_invoices i where i.organization_id=customer_invoice_fulfillments.organization_id and i.id=customer_invoice_fulfillments.invoice_id and public.has_permission(i.organization_id,'sales.invoice_view') and public.can_access_branch(i.organization_id,i.branch_id)));
create policy return_lines_read on public.sales_return_lines for select to authenticated using(exists(select 1 from public.sales_returns r where r.organization_id=sales_return_lines.organization_id and r.id=sales_return_lines.sales_return_id and public.has_permission(r.organization_id,'sales.return_view') and public.can_access_branch(r.organization_id,r.branch_id)));
create policy return_cost_allocations_read on public.sales_return_cost_allocations for select to authenticated using(exists(select 1 from public.sales_return_lines l join public.sales_returns r on r.organization_id=l.organization_id and r.id=l.sales_return_id where l.organization_id=sales_return_cost_allocations.organization_id and l.id=sales_return_cost_allocations.sales_return_line_id and public.has_permission(r.organization_id,'sales.return_view') and public.can_access_branch(r.organization_id,r.branch_id)));
grant select on public.customer_credit_exposure to authenticated;
