drop policy if exists purchase_requisitions_read on public.purchase_requisitions;
create policy purchase_requisitions_read on public.purchase_requisitions for select to authenticated using(public.has_permission(organization_id,'procurement.requisition_view') and public.can_access_branch(organization_id,requesting_branch_id));
drop policy if exists purchase_requisition_lines_read on public.purchase_requisition_lines;
create policy purchase_requisition_lines_read on public.purchase_requisition_lines for select to authenticated using(exists(select 1 from public.purchase_requisitions r where r.id=requisition_id and r.organization_id=organization_id and public.has_permission(organization_id,'procurement.requisition_view') and public.can_access_branch(organization_id,r.requesting_branch_id)));
drop policy if exists approval_requests_read on public.approval_requests;
create policy approval_requests_read on public.approval_requests for select to authenticated using(public.has_permission(organization_id,'procurement.requisition_view') and (branch_id is null or public.can_access_branch(organization_id,branch_id)));
drop policy if exists approval_actions_read on public.approval_actions;
create policy approval_actions_read on public.approval_actions for select to authenticated using(exists(select 1 from public.approval_requests r where r.id=approval_request_id and r.organization_id=organization_id and (r.branch_id is null or public.can_access_branch(organization_id,r.branch_id))));
drop policy if exists request_for_quotations_read on public.request_for_quotations;
create policy request_for_quotations_read on public.request_for_quotations for select to authenticated using(public.has_permission(organization_id,'procurement.rfq_view') and public.can_access_branch(organization_id,branch_id));
drop policy if exists rfq_lines_read on public.rfq_lines;
create policy rfq_lines_read on public.rfq_lines for select to authenticated using(exists(select 1 from public.request_for_quotations r where r.id=rfq_id and r.organization_id=organization_id and public.can_access_branch(organization_id,r.branch_id)));
drop policy if exists rfq_suppliers_read on public.rfq_suppliers;
create policy rfq_suppliers_read on public.rfq_suppliers for select to authenticated using(exists(select 1 from public.request_for_quotations r where r.id=rfq_id and r.organization_id=organization_id and public.can_access_branch(organization_id,r.branch_id)));
drop policy if exists supplier_quotations_read on public.supplier_quotations;
create policy supplier_quotations_read on public.supplier_quotations for select to authenticated using(public.has_permission(organization_id,'procurement.quote_view') and exists(select 1 from public.request_for_quotations r where r.id=rfq_id and r.organization_id=organization_id and public.can_access_branch(organization_id,r.branch_id)));
drop policy if exists supplier_quotation_lines_read on public.supplier_quotation_lines;
create policy supplier_quotation_lines_read on public.supplier_quotation_lines for select to authenticated using(exists(select 1 from public.supplier_quotations q join public.request_for_quotations r on r.id=q.rfq_id and r.organization_id=q.organization_id where q.id=supplier_quotation_lines.quotation_id and q.organization_id=supplier_quotation_lines.organization_id and public.can_access_branch(supplier_quotation_lines.organization_id,r.branch_id)));
drop policy if exists purchase_orders_read on public.purchase_orders;
create policy purchase_orders_read on public.purchase_orders for select to authenticated using(public.has_permission(organization_id,'procurement.po_view') and public.can_access_branch(organization_id,branch_id));
drop policy if exists purchase_order_lines_read on public.purchase_order_lines;
create policy purchase_order_lines_read on public.purchase_order_lines for select to authenticated using(exists(select 1 from public.purchase_orders p where p.id=purchase_order_id and p.organization_id=organization_id and public.can_access_branch(organization_id,p.branch_id)));
drop policy if exists goods_receipts_read on public.goods_receipts;
create policy goods_receipts_read on public.goods_receipts for select to authenticated using(public.has_permission(organization_id,'procurement.receipt_view') and public.can_access_branch(organization_id,branch_id));
drop policy if exists goods_receipt_lines_read on public.goods_receipt_lines;
create policy goods_receipt_lines_read on public.goods_receipt_lines for select to authenticated using(exists(select 1 from public.goods_receipts g where g.id=goods_receipt_id and g.organization_id=organization_id and public.can_access_branch(organization_id,g.branch_id)));
drop policy if exists purchase_returns_read on public.purchase_returns;
create policy purchase_returns_read on public.purchase_returns for select to authenticated using(public.has_permission(organization_id,'procurement.return_view') and public.can_access_branch(organization_id,branch_id));
drop policy if exists purchase_return_lines_read on public.purchase_return_lines;
create policy purchase_return_lines_read on public.purchase_return_lines for select to authenticated using(exists(select 1 from public.purchase_returns r where r.id=purchase_return_id and r.organization_id=organization_id and public.can_access_branch(organization_id,r.branch_id)));
