create table public.sales_settings(organization_id uuid primary key references public.organizations(id) on delete cascade,credit_limit_policy text not null default 'BLOCK' check(credit_limit_policy in('BLOCK','ALLOW_WITH_APPROVAL')),backorder_policy text not null default 'ALLOW' check(backorder_policy in('ALLOW','DISALLOW')),minimum_price_policy text not null default 'BLOCK' check(minimum_price_policy in('BLOCK','ALLOW_WITH_APPROVAL')),updated_at timestamptz not null default now(),updated_by uuid references auth.users(id));
create table public.customers(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,customer_code text not null,customer_type text not null check(customer_type in('INDIVIDUAL','BUSINESS')),display_name text not null,legal_name text,first_name text,last_name text,email text,phone text,alternate_phone text,tax_number text,registration_number text,default_currency text not null check(default_currency~'^[A-Z]{3}$'),default_price_list_id uuid,default_payment_terms text,credit_limit numeric(20,4) not null default 0 check(credit_limit>=0),credit_status text not null default 'NORMAL' check(credit_status in('NORMAL','ON_HOLD','BLOCKED')),sales_rep_id uuid references auth.users(id),notes text,status text not null default 'ACTIVE' check(status in('ACTIVE','INACTIVE','BLOCKED','ARCHIVED')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid not null references auth.users(id),unique(organization_id,id),unique(organization_id,customer_code),foreign key(organization_id,default_price_list_id) references public.price_lists(organization_id,id));
create table public.customer_contacts(id uuid primary key default gen_random_uuid(),organization_id uuid not null,customer_id uuid not null,name text not null,title text,email text,phone text,is_primary boolean not null default false,is_billing boolean not null default false,is_delivery boolean not null default false,is_purchasing boolean not null default false,notes text,status text not null default 'ACTIVE' check(status in('ACTIVE','INACTIVE')),created_at timestamptz not null default now(),foreign key(organization_id,customer_id) references public.customers(organization_id,id) on delete cascade);
create table public.customer_addresses(id uuid primary key default gen_random_uuid(),organization_id uuid not null,customer_id uuid not null,address_type text not null check(address_type in('BILLING','DELIVERY','OFFICE','HOME','OTHER')),line_1 text not null,line_2 text,city text,state_region text,postal_code text,country_code text not null,is_default_billing boolean not null default false,is_default_delivery boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,id),foreign key(organization_id,customer_id) references public.customers(organization_id,id) on delete cascade);
create table public.customer_documents(id uuid primary key default gen_random_uuid(),organization_id uuid not null,customer_id uuid not null,document_type text not null,file_name text not null,storage_path text not null,media_type text not null,size_bytes bigint not null check(size_bytes between 1 and 20971520),created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),foreign key(organization_id,customer_id) references public.customers(organization_id,id),unique(organization_id,storage_path));
create table public.sales_quotations(id uuid primary key default gen_random_uuid(),organization_id uuid not null,business_id uuid not null,quotation_number text not null,customer_id uuid not null,branch_id uuid not null,quotation_date date not null,expiry_date date,currency text not null,exchange_rate numeric(24,10) not null check(exchange_rate>0),base_currency text not null,price_list_id uuid,billing_address_snapshot jsonb,delivery_address_snapshot jsonb,customer_name_snapshot text not null,subtotal numeric(20,4) not null,discount numeric(20,4) not null default 0,tax numeric(20,4) not null default 0,total numeric(20,4) not null,base_currency_total numeric(20,4) not null,status text not null default 'DRAFT' check(status in('DRAFT','PENDING_APPROVAL','APPROVED','SENT','ACCEPTED','REJECTED','EXPIRED','CONVERTED','CANCELLED')),notes text,terms text,created_by uuid not null references auth.users(id),approved_by uuid references auth.users(id),approved_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,id),unique(organization_id,quotation_number),foreign key(organization_id,business_id) references public.businesses(organization_id,id),foreign key(organization_id,customer_id) references public.customers(organization_id,id),foreign key(organization_id,branch_id) references public.branches(organization_id,id),foreign key(organization_id,price_list_id) references public.price_lists(organization_id,id));
create table public.sales_quotation_lines(id uuid primary key default gen_random_uuid(),organization_id uuid not null,quotation_id uuid not null,product_variant_id uuid not null,packaging_id uuid not null,description_snapshot text not null,sku_snapshot text not null,entered_quantity numeric(24,6) not null check(entered_quantity>0),conversion_snapshot numeric(24,8) not null check(conversion_snapshot>0),base_quantity numeric(24,6) not null check(base_quantity>0),unit_price numeric(24,8) not null check(unit_price>=0),minimum_price_snapshot numeric(24,8),discount numeric(20,4) not null default 0,tax numeric(20,4) not null default 0,line_total numeric(20,4) not null,unique(organization_id,id),foreign key(organization_id,quotation_id) references public.sales_quotations(organization_id,id) on delete cascade,foreign key(organization_id,product_variant_id) references public.product_variants(organization_id,id),foreign key(organization_id,packaging_id) references public.product_variant_packaging(organization_id,id));
create table public.sales_orders(id uuid primary key default gen_random_uuid(),organization_id uuid not null,business_id uuid not null,sales_order_number text not null,customer_id uuid not null,originating_quotation_id uuid,branch_id uuid not null,fulfilment_warehouse_id uuid not null,fulfilment_location_id uuid not null,order_date date not null,requested_delivery_date date,currency text not null,exchange_rate numeric(24,10) not null check(exchange_rate>0),base_currency text not null,price_list_id uuid,subtotal numeric(20,4) not null,discount numeric(20,4) not null default 0,tax numeric(20,4) not null default 0,total numeric(20,4) not null,base_currency_total numeric(20,4) not null,payment_terms text,billing_address_snapshot jsonb,delivery_address_snapshot jsonb,customer_name_snapshot text not null,status text not null default 'DRAFT' check(status in('DRAFT','PENDING_APPROVAL','CONFIRMED','PARTIALLY_RESERVED','RESERVED','PARTIALLY_FULFILLED','FULFILLED','PARTIALLY_INVOICED','INVOICED','CANCELLED','CLOSED')),notes text,idempotency_key uuid,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,id),unique(organization_id,sales_order_number),unique(organization_id,idempotency_key),foreign key(organization_id,business_id) references public.businesses(organization_id,id),foreign key(organization_id,customer_id) references public.customers(organization_id,id),foreign key(organization_id,originating_quotation_id) references public.sales_quotations(organization_id,id),foreign key(organization_id,branch_id) references public.branches(organization_id,id),foreign key(organization_id,fulfilment_warehouse_id) references public.warehouses(organization_id,id),foreign key(organization_id,fulfilment_location_id) references public.storage_locations(organization_id,id));
create table public.sales_order_lines(id uuid primary key default gen_random_uuid(),organization_id uuid not null,sales_order_id uuid not null,product_variant_id uuid not null,packaging_id uuid not null,description_snapshot text not null,sku_snapshot text not null,ordered_quantity numeric(24,6) not null,conversion_snapshot numeric(24,8) not null,ordered_base_quantity numeric(24,6) not null,unit_price numeric(24,8) not null,discount numeric(20,4) not null default 0,tax numeric(20,4) not null default 0,line_total numeric(20,4) not null,reserved_base_quantity numeric(24,6) not null default 0,fulfilled_base_quantity numeric(24,6) not null default 0,cancelled_base_quantity numeric(24,6) not null default 0,backordered_base_quantity numeric(24,6) not null default 0,reservation_id uuid,unique(organization_id,id),foreign key(organization_id,sales_order_id) references public.sales_orders(organization_id,id) on delete cascade,foreign key(organization_id,product_variant_id) references public.product_variants(organization_id,id),foreign key(organization_id,packaging_id) references public.product_variant_packaging(organization_id,id),foreign key(organization_id,reservation_id) references public.inventory_reservations(organization_id,id));
create table public.sales_fulfillments(id uuid primary key default gen_random_uuid(),organization_id uuid not null,business_id uuid not null,fulfilment_number text not null,sales_order_id uuid not null,customer_id uuid not null,branch_id uuid not null,warehouse_id uuid not null,storage_location_id uuid not null,delivery_address_snapshot jsonb,fulfilled_at timestamptz not null,fulfilled_by uuid not null references auth.users(id),status text not null default 'DRAFT' check(status in('DRAFT','POSTED','REVERSED')),notes text,idempotency_key uuid not null,inventory_transaction_id uuid,created_at timestamptz not null default now(),unique(organization_id,id),unique(organization_id,fulfilment_number),unique(organization_id,idempotency_key),foreign key(organization_id,business_id) references public.businesses(organization_id,id),foreign key(organization_id,sales_order_id) references public.sales_orders(organization_id,id),foreign key(organization_id,customer_id) references public.customers(organization_id,id),foreign key(organization_id,branch_id) references public.branches(organization_id,id),foreign key(organization_id,warehouse_id) references public.warehouses(organization_id,id),foreign key(organization_id,storage_location_id) references public.storage_locations(organization_id,id),foreign key(organization_id,inventory_transaction_id) references public.inventory_transactions(organization_id,id));
create table public.sales_fulfillment_lines(id uuid primary key default gen_random_uuid(),organization_id uuid not null,fulfilment_id uuid not null,sales_order_line_id uuid not null,product_variant_id uuid not null,packaging_id uuid not null,entered_quantity numeric(24,6) not null,conversion_snapshot numeric(24,8) not null,base_quantity numeric(24,6) not null,revenue_base numeric(28,8) not null,inventory_cost_base numeric(28,8) not null default 0,gross_margin_base numeric(28,8) not null default 0,unique(organization_id,id),foreign key(organization_id,fulfilment_id) references public.sales_fulfillments(organization_id,id) on delete cascade,foreign key(organization_id,sales_order_line_id) references public.sales_order_lines(organization_id,id),foreign key(organization_id,product_variant_id) references public.product_variants(organization_id,id),foreign key(organization_id,packaging_id) references public.product_variant_packaging(organization_id,id));
create table public.customer_invoices(id uuid primary key default gen_random_uuid(),organization_id uuid not null,business_id uuid not null,invoice_number text not null,customer_id uuid not null,sales_order_id uuid,branch_id uuid not null,invoice_date date not null,due_date date,currency text not null,exchange_rate numeric(24,10) not null check(exchange_rate>0),base_currency text not null,billing_address_snapshot jsonb,customer_name_snapshot text not null,subtotal numeric(20,4) not null,discount numeric(20,4) not null default 0,tax numeric(20,4) not null default 0,total numeric(20,4) not null,base_currency_total numeric(20,4) not null,credit_note_total_base numeric(20,4) not null default 0,amount_paid_base numeric(20,4) not null default 0,status text not null default 'DRAFT' check(status in('DRAFT','ISSUED','PARTIALLY_PAID','PAID','OVERDUE','DISPUTED','VOID','CREDITED')),payment_terms text,notes text,idempotency_key uuid not null,created_by uuid not null references auth.users(id),issued_by uuid references auth.users(id),issued_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,id),unique(organization_id,invoice_number),unique(organization_id,idempotency_key),foreign key(organization_id,business_id) references public.businesses(organization_id,id),foreign key(organization_id,customer_id) references public.customers(organization_id,id),foreign key(organization_id,sales_order_id) references public.sales_orders(organization_id,id),foreign key(organization_id,branch_id) references public.branches(organization_id,id));
create table public.customer_invoice_lines(id uuid primary key default gen_random_uuid(),organization_id uuid not null,invoice_id uuid not null,sales_order_line_id uuid,sales_fulfillment_line_id uuid,product_variant_id uuid,description_snapshot text not null,sku_snapshot text,quantity numeric(24,6) not null check(quantity>0),unit_price numeric(24,8) not null check(unit_price>=0),discount numeric(20,4) not null default 0,tax numeric(20,4) not null default 0,line_total numeric(20,4) not null,unique(organization_id,id),foreign key(organization_id,invoice_id) references public.customer_invoices(organization_id,id) on delete cascade,foreign key(organization_id,sales_order_line_id) references public.sales_order_lines(organization_id,id),foreign key(organization_id,sales_fulfillment_line_id) references public.sales_fulfillment_lines(organization_id,id),foreign key(organization_id,product_variant_id) references public.product_variants(organization_id,id));
create table public.customer_invoice_fulfillments(organization_id uuid not null,invoice_id uuid not null,fulfilment_id uuid not null,primary key(invoice_id,fulfilment_id),foreign key(organization_id,invoice_id) references public.customer_invoices(organization_id,id) on delete cascade,foreign key(organization_id,fulfilment_id) references public.sales_fulfillments(organization_id,id));
create table public.sales_return_reasons(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,code text not null,name text not null,is_active boolean not null default true,requires_notes boolean not null default false,created_by uuid not null references auth.users(id),unique(organization_id,id),unique(organization_id,code));
create table public.sales_returns(id uuid primary key default gen_random_uuid(),organization_id uuid not null,business_id uuid not null,return_number text not null,customer_id uuid not null,sales_order_id uuid,sales_fulfilment_id uuid,customer_invoice_id uuid,branch_id uuid not null,return_date timestamptz not null,reason_id uuid not null,status text not null default 'REQUESTED' check(status in('REQUESTED','APPROVED','RECEIVED','INSPECTED','POSTED','REJECTED','CANCELLED')),notes text,idempotency_key uuid not null,inventory_transaction_id uuid,credit_note_id uuid,created_by uuid not null references auth.users(id),posted_at timestamptz,created_at timestamptz not null default now(),unique(organization_id,id),unique(organization_id,return_number),unique(organization_id,idempotency_key),foreign key(organization_id,business_id) references public.businesses(organization_id,id),foreign key(organization_id,customer_id) references public.customers(organization_id,id),foreign key(organization_id,sales_order_id) references public.sales_orders(organization_id,id),foreign key(organization_id,sales_fulfilment_id) references public.sales_fulfillments(organization_id,id),foreign key(organization_id,customer_invoice_id) references public.customer_invoices(organization_id,id),foreign key(organization_id,branch_id) references public.branches(organization_id,id),foreign key(organization_id,reason_id) references public.sales_return_reasons(organization_id,id),foreign key(organization_id,inventory_transaction_id) references public.inventory_transactions(organization_id,id));
create table public.sales_return_lines(id uuid primary key default gen_random_uuid(),organization_id uuid not null,sales_return_id uuid not null,sales_fulfillment_line_id uuid not null,product_variant_id uuid not null,packaging_id uuid not null,requested_quantity numeric(24,6) not null,received_quantity numeric(24,6) not null default 0,accepted_quantity numeric(24,6) not null default 0,rejected_quantity numeric(24,6) not null default 0,conversion_snapshot numeric(24,8) not null,accepted_base_quantity numeric(24,6) not null default 0,condition text,disposition text check(disposition in('RESTOCK_NORMAL','RESTOCK_DAMAGED','REJECT_RETURN','SCRAP')),destination_location_id uuid,return_unit_cost_base numeric(24,8),notes text,unique(organization_id,id),foreign key(organization_id,sales_return_id) references public.sales_returns(organization_id,id) on delete cascade,foreign key(organization_id,sales_fulfillment_line_id) references public.sales_fulfillment_lines(organization_id,id),foreign key(organization_id,product_variant_id) references public.product_variants(organization_id,id),foreign key(organization_id,packaging_id) references public.product_variant_packaging(organization_id,id),foreign key(organization_id,destination_location_id) references public.storage_locations(organization_id,id),check(accepted_quantity+rejected_quantity<=received_quantity));
create table public.customer_credit_notes(id uuid primary key default gen_random_uuid(),organization_id uuid not null,credit_note_number text not null,customer_id uuid not null,customer_invoice_id uuid,sales_return_id uuid,branch_id uuid not null,credit_date date not null,currency text not null,exchange_rate numeric(24,10) not null check(exchange_rate>0),subtotal numeric(20,4) not null,tax numeric(20,4) not null default 0,total numeric(20,4) not null,base_currency_total numeric(20,4) not null,reason text not null,status text not null default 'DRAFT' check(status in('DRAFT','APPROVED','ISSUED','VOID')),refund_disposition text not null default 'CUSTOMER_CREDIT' check(refund_disposition in('CUSTOMER_CREDIT','REFUND_PENDING')),idempotency_key uuid not null,created_by uuid not null references auth.users(id),approved_by uuid references auth.users(id),approved_at timestamptz,created_at timestamptz not null default now(),unique(organization_id,id),unique(organization_id,credit_note_number),unique(organization_id,idempotency_key),foreign key(organization_id,customer_id) references public.customers(organization_id,id),foreign key(organization_id,customer_invoice_id) references public.customer_invoices(organization_id,id),foreign key(organization_id,sales_return_id) references public.sales_returns(organization_id,id),foreign key(organization_id,branch_id) references public.branches(organization_id,id));
alter table public.sales_returns add constraint sales_returns_credit_note_fk foreign key(organization_id,credit_note_id) references public.customer_credit_notes(organization_id,id);
create table public.sales_activity(id bigint generated always as identity primary key,organization_id uuid not null references public.organizations(id) on delete cascade,document_type text not null,document_id uuid not null,action text not null,actor_id uuid references auth.users(id),details jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create index customers_search_idx on public.customers(organization_id,status,display_name,customer_code);create index sales_quotes_status_idx on public.sales_quotations(organization_id,branch_id,status,expiry_date);create index sales_orders_queue_idx on public.sales_orders(organization_id,branch_id,status,requested_delivery_date);create index sales_order_lines_open_idx on public.sales_order_lines(organization_id,sales_order_id,product_variant_id) where fulfilled_base_quantity+cancelled_base_quantity<ordered_base_quantity;create index sales_fulfillments_order_idx on public.sales_fulfillments(organization_id,sales_order_id,fulfilled_at desc);create index customer_invoices_due_idx on public.customer_invoices(organization_id,branch_id,customer_id,status,due_date);create index sales_returns_customer_idx on public.sales_returns(organization_id,customer_id,status,return_date desc);create index sales_activity_document_idx on public.sales_activity(organization_id,document_type,document_id,created_at desc);
create view public.customer_receivables with(security_invoker=true) as select i.organization_id,i.customer_id,sum(case when i.status not in('DRAFT','VOID') then i.base_currency_total-i.credit_note_total_base-i.amount_paid_base else 0 end) outstanding_base,sum(case when i.status not in('DRAFT','VOID') and i.due_date<current_date then i.base_currency_total-i.credit_note_total_base-i.amount_paid_base else 0 end) overdue_base,min(i.due_date) filter(where i.status not in('DRAFT','VOID') and i.base_currency_total>i.credit_note_total_base+i.amount_paid_base) oldest_due_date from public.customer_invoices i group by i.organization_id,i.customer_id;

-- Transactional projections and immutable costing links used by the Sales RPC layer.
alter table public.sales_quotations add column idempotency_key uuid, add column request_hash text;
alter table public.sales_orders add column request_hash text, add column confirmed_at timestamptz, add column cancelled_at timestamptz, add column credit_override_by uuid references auth.users(id);
alter table public.sales_fulfillments add column request_hash text not null;
alter table public.sales_fulfillment_lines add column inventory_movement_id uuid, add column gross_profit_base numeric(28,8) not null default 0;
alter table public.customer_invoices add column request_hash text not null;
alter table public.customer_invoice_lines add column conversion_snapshot numeric(24,8) not null check(conversion_snapshot>0);
alter table public.sales_returns add column request_hash text not null;
alter table public.customer_credit_notes add column request_hash text not null, add column issued_at timestamptz, add column issued_by uuid references auth.users(id);

create unique index sales_quotations_idempotency_idx on public.sales_quotations(organization_id,idempotency_key) where idempotency_key is not null;
create unique index sales_orders_quotation_once_idx on public.sales_orders(organization_id,originating_quotation_id) where originating_quotation_id is not null;
create unique index sales_credit_return_once_idx on public.customer_credit_notes(organization_id,sales_return_id) where sales_return_id is not null and status<>'VOID';
create index sales_order_backorders_idx on public.sales_order_lines(organization_id,product_variant_id) where backordered_base_quantity>0;

alter table public.sales_order_lines add constraint sales_order_line_quantities_check check(
  ordered_quantity>0 and conversion_snapshot>0 and ordered_base_quantity>0 and unit_price>=0
  and reserved_base_quantity>=0 and fulfilled_base_quantity>=0 and cancelled_base_quantity>=0 and backordered_base_quantity>=0
  and fulfilled_base_quantity+cancelled_base_quantity<=ordered_base_quantity
  and reserved_base_quantity<=ordered_base_quantity-fulfilled_base_quantity-cancelled_base_quantity
);
alter table public.sales_fulfillment_lines add constraint sales_fulfillment_line_quantities_check check(entered_quantity>0 and conversion_snapshot>0 and base_quantity>0);
alter table public.sales_fulfillment_lines add constraint sales_fulfillment_line_movement_fk foreign key(organization_id,inventory_movement_id) references public.inventory_movements(organization_id,id);
alter table public.sales_fulfillment_lines add constraint sales_fulfillment_line_once unique(fulfilment_id,sales_order_line_id);
alter table public.sales_return_lines add constraint sales_return_line_quantities_check check(requested_quantity>0 and received_quantity>=0 and accepted_quantity>=0 and rejected_quantity>=0 and accepted_base_quantity>=0 and conversion_snapshot>0);

alter table public.inventory_cost_allocations add constraint inventory_cost_allocations_org_id_key unique(organization_id,id);
create table public.sales_return_cost_allocations(
 id uuid primary key default gen_random_uuid(), organization_id uuid not null, sales_return_line_id uuid not null,
 original_cost_allocation_id uuid, quantity_base numeric(24,6) not null check(quantity_base>0), unit_cost_base numeric(24,8) not null check(unit_cost_base>=0),
 created_at timestamptz not null default now(), unique(organization_id,id),
 foreign key(organization_id,sales_return_line_id) references public.sales_return_lines(organization_id,id) on delete cascade,
 foreign key(organization_id,original_cost_allocation_id) references public.inventory_cost_allocations(organization_id,id)
);

create view public.customer_credit_exposure with(security_invoker=true) as
select c.organization_id,c.id customer_id,
 coalesce(r.outstanding_base,0) outstanding_receivables_base,
 coalesce(sum(case when o.status in('CONFIRMED','PARTIALLY_RESERVED','RESERVED','PARTIALLY_FULFILLED')
  then greatest(o.base_currency_total-coalesce(inv.invoiced_base,0),0) else 0 end),0) confirmed_commitments_base,
 coalesce(r.outstanding_base,0)+coalesce(sum(case when o.status in('CONFIRMED','PARTIALLY_RESERVED','RESERVED','PARTIALLY_FULFILLED')
  then greatest(o.base_currency_total-coalesce(inv.invoiced_base,0),0) else 0 end),0) exposure_base
from public.customers c
left join public.customer_receivables r on r.organization_id=c.organization_id and r.customer_id=c.id
left join public.sales_orders o on o.organization_id=c.organization_id and o.customer_id=c.id
left join lateral(select sum(i.base_currency_total) invoiced_base from public.customer_invoices i where i.organization_id=o.organization_id and i.sales_order_id=o.id and i.status not in('DRAFT','VOID')) inv on true
group by c.organization_id,c.id,r.outstanding_base;
