create or replace function public.create_rfq(target_organization_id uuid,target_business_id uuid,target_requisition_id uuid,target_branch_id uuid,target_location_id uuid,target_required_date date,target_deadline timestamptz,target_terms text,target_notes text,target_supplier_ids uuid[],target_lines jsonb)
returns uuid language plpgsql security definer set search_path='' as $$ declare new_id uuid:=gen_random_uuid(); number text; supplier_id uuid; line jsonb; package record; begin
 if not public.has_permission(target_organization_id,'procurement.rfq_create') or not public.can_access_branch(target_organization_id,target_branch_id) then raise exception using errcode='42501',message='PERMISSION_DENIED'; end if;
 if not exists(select 1 from public.storage_locations where organization_id=target_organization_id and id=target_location_id and branch_id=target_branch_id) then raise exception using errcode='P0001',message='INVALID_DESTINATION'; end if;
 number:=public.next_procurement_number(target_organization_id,'RFQ'); insert into public.request_for_quotations(id,organization_id,business_id,rfq_number,requisition_id,branch_id,delivery_location_id,required_delivery_date,response_deadline,terms,notes,created_by) values(new_id,target_organization_id,target_business_id,number,target_requisition_id,target_branch_id,target_location_id,target_required_date,target_deadline,nullif(trim(target_terms),''),nullif(trim(target_notes),''),auth.uid());
 foreach supplier_id in array target_supplier_ids loop if not exists(select 1 from public.suppliers where organization_id=target_organization_id and id=supplier_id and status='ACTIVE') then raise exception using errcode='P0001',message='SUPPLIER_NOT_ACTIVE'; end if; insert into public.rfq_suppliers(organization_id,rfq_id,supplier_id) values(target_organization_id,new_id,supplier_id); end loop;
 for line in select value from jsonb_array_elements(target_lines) loop select p.id,p.product_variant_id,p.conversion_to_base,v.name into package from public.product_variant_packaging p join public.product_variants v on v.organization_id=p.organization_id and v.id=p.product_variant_id where p.organization_id=target_organization_id and p.id=(line->>'packaging_id')::uuid and p.product_variant_id=(line->>'product_variant_id')::uuid; if not found then raise exception using errcode='P0001',message='INVALID_PACKAGING'; end if; insert into public.rfq_lines(organization_id,rfq_id,requisition_line_id,product_variant_id,packaging_id,requested_quantity,conversion_snapshot,product_description_snapshot) values(target_organization_id,new_id,nullif(line->>'requisition_line_id','')::uuid,package.product_variant_id,package.id,(line->>'quantity')::numeric,package.conversion_to_base,package.name); end loop;
 insert into public.procurement_activity(organization_id,document_type,document_id,action,actor_id) values(target_organization_id,'RFQ',new_id,'CREATED',auth.uid()); return new_id;
end $$;

create or replace function public.issue_rfq(target_organization_id uuid,target_rfq_id uuid) returns void language plpgsql security definer set search_path='' as $$ declare doc public.request_for_quotations%rowtype; begin select * into doc from public.request_for_quotations where organization_id=target_organization_id and id=target_rfq_id for update; if not found or doc.status<>'DRAFT' or not public.has_permission(target_organization_id,'procurement.rfq_issue') or not public.can_access_branch(target_organization_id,doc.branch_id) then raise exception using errcode='42501',message='PERMISSION_DENIED'; end if; update public.request_for_quotations set status='ISSUED',updated_at=now() where id=doc.id; insert into public.procurement_activity(organization_id,document_type,document_id,action,actor_id) values(target_organization_id,'RFQ',doc.id,'ISSUED',auth.uid()); end $$;

create or replace function public.record_supplier_quotation(target_organization_id uuid,target_rfq_id uuid,target_supplier_id uuid,target_quote_number text,target_quote_date date,target_expiry_date date,target_currency text,target_exchange_rate numeric,target_delivery_days integer,target_payment_terms text,target_shipping_terms text,target_discount numeric,target_tax numeric,target_freight numeric,target_notes text,target_lines jsonb)
returns uuid language plpgsql security definer set search_path='' as $$ declare new_id uuid:=gen_random_uuid(); base_currency text; subtotal numeric:=0; total numeric; line jsonb; rfq_line public.rfq_lines%rowtype; line_total numeric; begin
 if not public.has_permission(target_organization_id,'procurement.quote_create') then raise exception using errcode='42501',message='PERMISSION_DENIED'; end if; if not exists(select 1 from public.rfq_suppliers rs join public.request_for_quotations r on r.id=rs.rfq_id and r.organization_id=rs.organization_id where rs.organization_id=target_organization_id and rs.rfq_id=target_rfq_id and rs.supplier_id=target_supplier_id and r.status in ('ISSUED','RESPONSES_PENDING','RESPONSES_RECEIVED','EVALUATION')) then raise exception using errcode='P0001',message='INVALID_RFQ_SUPPLIER'; end if;
 select currency_code into base_currency from public.organizations where id=target_organization_id; for line in select value from jsonb_array_elements(target_lines) loop subtotal:=subtotal+round((line->>'quantity')::numeric*(line->>'unit_price')::numeric-coalesce(nullif(line->>'discount','')::numeric,0)+coalesce(nullif(line->>'tax','')::numeric,0),4); end loop; total:=subtotal-target_discount+target_tax+target_freight;
 insert into public.supplier_quotations(id,organization_id,rfq_id,supplier_id,quote_number,quote_date,expiry_date,currency,exchange_rate,base_currency,delivery_period_days,payment_terms,shipping_terms,subtotal,discount,tax,freight,total,notes,created_by) values(new_id,target_organization_id,target_rfq_id,target_supplier_id,trim(target_quote_number),target_quote_date,target_expiry_date,target_currency,target_exchange_rate,base_currency,target_delivery_days,target_payment_terms,target_shipping_terms,subtotal,target_discount,target_tax,target_freight,total,target_notes,auth.uid());
 for line in select value from jsonb_array_elements(target_lines) loop select * into rfq_line from public.rfq_lines where organization_id=target_organization_id and rfq_id=target_rfq_id and id=(line->>'rfq_line_id')::uuid; if not found then raise exception using errcode='P0001',message='INVALID_RFQ_LINE'; end if; line_total:=round((line->>'quantity')::numeric*(line->>'unit_price')::numeric-coalesce(nullif(line->>'discount','')::numeric,0)+coalesce(nullif(line->>'tax','')::numeric,0),4); insert into public.supplier_quotation_lines(organization_id,quotation_id,rfq_line_id,product_variant_id,packaging_id,offered_quantity,conversion_snapshot,unit_price,discount,tax,line_total,expected_delivery_date,is_alternative) values(target_organization_id,new_id,rfq_line.id,rfq_line.product_variant_id,rfq_line.packaging_id,(line->>'quantity')::numeric,rfq_line.conversion_snapshot,(line->>'unit_price')::numeric,coalesce(nullif(line->>'discount','')::numeric,0),coalesce(nullif(line->>'tax','')::numeric,0),line_total,nullif(line->>'expected_delivery_date','')::date,coalesce((line->>'is_alternative')::boolean,false)); insert into public.supplier_price_history(organization_id,supplier_id,product_variant_id,packaging_id,quoted_price,effective_date,currency,exchange_rate,base_currency,base_currency_price,source_quotation_id) values(target_organization_id,target_supplier_id,rfq_line.product_variant_id,rfq_line.packaging_id,(line->>'unit_price')::numeric,target_quote_date,target_currency,target_exchange_rate,base_currency,round((line->>'unit_price')::numeric*target_exchange_rate,8),new_id); end loop;
 update public.rfq_suppliers set status='RESPONDED' where rfq_id=target_rfq_id and supplier_id=target_supplier_id; update public.request_for_quotations set status='RESPONSES_RECEIVED',updated_at=now() where id=target_rfq_id; return new_id;
end $$;

create or replace function public.award_quotation(target_organization_id uuid,target_quotation_id uuid,target_awards jsonb)
returns void language plpgsql security definer set search_path='' as $$ declare quote public.supplier_quotations%rowtype; award jsonb; quote_line public.supplier_quotation_lines%rowtype; begin select * into quote from public.supplier_quotations where organization_id=target_organization_id and id=target_quotation_id for update; if not found or quote.status<>'RECORDED' or not public.has_permission(target_organization_id,'procurement.quote_select') then raise exception using errcode='42501',message='PERMISSION_DENIED'; end if; for award in select value from jsonb_array_elements(target_awards) loop select * into quote_line from public.supplier_quotation_lines where organization_id=target_organization_id and quotation_id=quote.id and id=(award->>'quotation_line_id')::uuid for update; if not found or (award->>'quantity')::numeric>quote_line.offered_quantity then raise exception using errcode='P0001',message='INVALID_AWARD'; end if; update public.supplier_quotation_lines set awarded_quantity=(award->>'quantity')::numeric where id=quote_line.id; end loop; update public.supplier_quotations set status='SELECTED' where id=quote.id; update public.rfq_suppliers set status='AWARDED' where rfq_id=quote.rfq_id and supplier_id=quote.supplier_id; update public.request_for_quotations set status='AWARDED',updated_at=now() where id=quote.rfq_id; insert into public.procurement_activity(organization_id,document_type,document_id,action,actor_id) values(target_organization_id,'RFQ',quote.rfq_id,'QUOTATION_AWARDED',auth.uid()); end $$;

create or replace function public.allocate_landed_cost(target_organization_id uuid,target_goods_receipt_id uuid,target_cost_type text,target_description text,target_currency text,target_exchange_rate numeric,target_amount numeric,target_method text,target_manual_allocations jsonb default null)
returns uuid language plpgsql security definer set search_path='' as $$ declare new_id uuid:=gen_random_uuid(); total_basis numeric; allocation record; allocated numeric; base_amount numeric:=round(target_amount*target_exchange_rate,4); begin if not public.has_permission(target_organization_id,'procurement.receipt_post') then raise exception using errcode='42501',message='PERMISSION_DENIED'; end if; if not exists(select 1 from public.goods_receipts where organization_id=target_organization_id and id=target_goods_receipt_id and status='POSTED') then raise exception using errcode='P0001',message='GRN_NOT_POSTED'; end if; insert into public.landed_costs(id,organization_id,goods_receipt_id,cost_type,description,currency,exchange_rate,amount,base_currency_amount,allocation_method,created_by) values(new_id,target_organization_id,target_goods_receipt_id,target_cost_type,target_description,target_currency,target_exchange_rate,target_amount,base_amount,target_method,auth.uid()); if target_method='MANUAL' then for allocation in select value from jsonb_array_elements(target_manual_allocations) loop insert into public.landed_cost_allocations(organization_id,landed_cost_id,goods_receipt_line_id,allocated_amount_base) values(target_organization_id,new_id,(allocation.value->>'goods_receipt_line_id')::uuid,(allocation.value->>'amount_base')::numeric); end loop; else select case target_method when 'BY_VALUE' then sum(accepted_base_quantity*unit_purchase_cost_base) else sum(accepted_base_quantity) end into total_basis from public.goods_receipt_lines where organization_id=target_organization_id and goods_receipt_id=target_goods_receipt_id; for allocation in select id,case target_method when 'BY_VALUE' then accepted_base_quantity*unit_purchase_cost_base else accepted_base_quantity end basis from public.goods_receipt_lines where organization_id=target_organization_id and goods_receipt_id=target_goods_receipt_id loop allocated:=round(base_amount*allocation.basis/nullif(total_basis,0),8); insert into public.landed_cost_allocations(organization_id,landed_cost_id,goods_receipt_line_id,allocated_amount_base) values(target_organization_id,new_id,allocation.id,allocated); end loop; end if; if abs((select coalesce(sum(allocated_amount_base),0) from public.landed_cost_allocations where landed_cost_id=new_id)-base_amount)>0.01 then raise exception using errcode='P0001',message='LANDED_COST_ALLOCATION_MISMATCH'; end if; return new_id; end $$;

create or replace function public.approve_supplier_invoice(target_organization_id uuid,target_invoice_id uuid) returns void language plpgsql security definer set search_path='' as $$ declare invoice public.supplier_invoices%rowtype; begin select * into invoice from public.supplier_invoices where organization_id=target_organization_id and id=target_invoice_id for update; if not found or invoice.status not in ('REVIEW','DISPUTED') or not public.has_permission(target_organization_id,'procurement.invoice_approve') then raise exception using errcode='42501',message='PERMISSION_DENIED'; end if; update public.supplier_invoices set status='APPROVED',approved_by=auth.uid(),approved_at=now(),updated_at=now() where id=invoice.id; insert into public.audit_events(organization_id,actor_id,action,entity_type,entity_id,after_data) values(target_organization_id,auth.uid(),'procurement.invoice_approved','supplier_invoice',invoice.id,jsonb_build_object('total',invoice.total,'match_status',invoice.match_status)); end $$;

do $$ declare f record; begin for f in select p.oid::regprocedure signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('create_rfq','issue_rfq','record_supplier_quotation','award_quotation','allocate_landed_cost','approve_supplier_invoice') loop execute format('revoke all on function %s from public,anon',f.signature); execute format('grant execute on function %s to authenticated',f.signature); end loop; end $$;
