export type QuoteMetric={id:string;unitPrice:number;freight:number;tax:number;discount:number;exchangeRate:number;deliveryDays:number;paymentTermDays:number};
export function baseAmount(amount:number,exchangeRate:number){return Math.round(amount*exchangeRate*10000)/10000}
export function purchaseTotal(subtotal:number,discount:number,tax:number,freight:number,other=0){return Math.round((subtotal-discount+tax+freight+other)*10000)/10000}
export function receiptOutstanding(orderedBase:number,acceptedBase:number){return Math.max(0,Math.round((orderedBase-acceptedBase)*1e6)/1e6)}
export function receiptState(lines:Array<{orderedBase:number;acceptedBase:number}>){const received=lines.reduce((n,x)=>n+x.acceptedBase,0);if(received===0)return"APPROVED";return lines.every(x=>x.acceptedBase>=x.orderedBase)?"FULLY_RECEIVED":"PARTIALLY_RECEIVED"}
export function allocateLandedCost(amount:number,bases:number[]){const total=bases.reduce((a,b)=>a+b,0);if(total<=0)throw new Error("Allocation basis must be positive");let used=0;return bases.map((basis,index)=>{if(index===bases.length-1)return Math.round((amount-used)*1e8)/1e8;const part=Math.round(amount*basis/total*1e8)/1e8;used+=part;return part})}
export function compareQuotes(quotes:QuoteMetric[]){return [...quotes].map(q=>({...q,landedBase:baseAmount(q.unitPrice+q.freight+q.tax-q.discount,q.exchangeRate)})).sort((a,b)=>a.landedBase-b.landedBase||a.deliveryDays-b.deliveryDays)}
export function invoiceMatch(invoice:number,po:number,received:number,tolerance=.01){if(Math.abs(invoice-po)<=tolerance&&Math.abs(invoice-received)<=tolerance)return"MATCHED";if(Math.abs(invoice-po)>tolerance)return"PRICE_VARIANCE";return"QUANTITY_VARIANCE"}
export function supplierPerformance(rows:Array<{ordered:number;accepted:number;rejected:number;onTime:boolean}>){const ordered=rows.reduce((n,x)=>n+x.ordered,0);const accepted=rows.reduce((n,x)=>n+x.accepted,0);const rejected=rows.reduce((n,x)=>n+x.rejected,0);return{fillRate:ordered?accepted/ordered*100:0,rejectionRate:accepted+rejected?rejected/(accepted+rejected)*100:0,onTimeRate:rows.length?rows.filter(x=>x.onTime).length/rows.length*100:0}}
export function procurementError(message:string){const code=["PERMISSION_DENIED","SELF_APPROVAL_DENIED","OVER_RECEIPT_NOT_ALLOWED","SUPPLIER_NOT_ACTIVE","INVALID_PACKAGING","INVOICE_TOTAL_MISMATCH","PO_NOT_RECEIVABLE","IMMUTABLE_PROCUREMENT_HISTORY","APPROVED_PO_IMMUTABLE"].find(x=>message.includes(x));return({PERMISSION_DENIED:"You do not have permission for this procurement action.",SELF_APPROVAL_DENIED:"This policy does not allow self-approval.",OVER_RECEIPT_NOT_ALLOWED:"Accepted quantity exceeds the permitted purchase-order quantity.",SUPPLIER_NOT_ACTIVE:"Choose an active supplier.",INVALID_PACKAGING:"The selected packaging does not belong to this product.",INVOICE_TOTAL_MISMATCH:"The supplier invoice total does not balance.",PO_NOT_RECEIVABLE:"This purchase order is not ready to receive.",IMMUTABLE_PROCUREMENT_HISTORY:"Historical procurement records cannot be changed.",APPROVED_PO_IMMUTABLE:"Approved purchase-order terms require a new revision."} as Record<string,string>)[code??""]??"Procurement operation failed."}
